# =========================================================
# BuyQK AI - Entity / Understanding Node
# =========================================================
#
# Phase 2 responsibility:
#
#   User Message
#        ↓
#   AI Understanding
#        ↓
#   Current-turn entities
#        ↓
#   Accumulated transaction state
#        ↓
#   GraphState
#
# This node is an UNDERSTANDING layer.
#
# It must NOT decide:
#
#   - which tool should execute
#   - whether an order should be created
#   - whether an order should be cancelled
#   - whether an order should be tracked
#   - whether a conversational response should end
#
# Those decisions belong to planner_node.py.
#
# This node may understand:
#
#   - product references
#   - quantity
#   - order references
#   - address references
#   - payment references
#   - language/context
#   - current-turn intent
#   - references to previous conversation
#
# Backend remains authoritative for:
#
#   - product_id
#   - price
#   - stock
#   - order_id generated by backend
#   - bill
#   - payment validity
#   - address authorization
#   - order status
#
# =========================================================


from __future__ import annotations

import re
import uuid

from typing import Any, Literal, Optional

from langchain_core.messages import (
    HumanMessage,
    SystemMessage,
)

from pydantic import BaseModel, Field

from ai_engine.graph.state import GraphState
from ai_engine.llm.client import get_llm


# =========================================================
# LLM ENTITY OUTPUT
# =========================================================


class LLMEntityOutput(BaseModel):
    """
    Structured understanding of the CURRENT user message.

    This model intentionally contains user-understandable
    information only.

    Database identifiers must never be hallucinated.
    """

    product_name: Optional[str] = Field(
        default=None,
        description=(
            "The product the user is referring to. "
            "Understand the meaning semantically."
        ),
    )

    quantity: Optional[int] = Field(
        default=None,
        ge=1,
        description=(
            "Explicit quantity understood from the "
            "current user message."
        ),
    )

    order_id: Optional[int] = Field(
        default=None,
        ge=1,
        description=(
            "Order ID explicitly referred to by the user."
        ),
    )

    address_id: Optional[int] = Field(
        default=None,
        ge=1,
        description=(
            "Saved address ID explicitly selected by "
            "the user."
        ),
    )

    address_text: Optional[str] = Field(
        default=None,
        description=(
            "Natural-language address or delivery location "
            "understood from the message."
        ),
    )

    payment_method: Optional[str] = Field(
        default=None,
        description=(
            "Payment method understood from the current "
            "message. Do not invent unavailable methods."
        ),
    )


# =========================================================
# CURRENT-TURN INTENT
# =========================================================


class IntentDecision(BaseModel):
    """
    Understand what the user means NOW.

    IMPORTANT:

    This is understanding, not execution planning.

    The planner node decides what action/tool should happen
    after this understanding has been produced.
    """

    intent: Literal[
        "product_search",
        "order_create",
        "order_tracking",
        "order_cancel",
        "customer_support",
        "general",
    ]

    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
    )


# =========================================================
# LLM
# =========================================================


llm = get_llm()

structured_entity_llm = llm.with_structured_output(
    LLMEntityOutput
)

structured_intent_llm = llm.with_structured_output(
    IntentDecision
)


# =========================================================
# ENTITY SYSTEM PROMPT
# =========================================================


ENTITY_SYSTEM_PROMPT = """
You are BuyQK's AI understanding engine.

Your responsibility is ONLY to understand the user's
CURRENT message.

Do not decide which backend tool should execute.

Do not create an order.

Do not modify an order.

Do not calculate money.

Do not invent database identifiers.

Return only information that can be confidently understood
from the current message and conversation context.

SUPPORTED ENTITY CONCEPTS:

- product_name
- quantity
- order_id
- address_id
- address_text
- payment_method

IMPORTANT:

product_id is NOT an extraction field.

Never invent product_id.

Never calculate:

- price
- subtotal
- total
- tax
- delivery charge
- discount

Never invent:

- order ID
- stock
- payment validity
- delivery availability

Those values belong to backend/database systems.

============================================================
LANGUAGE
============================================================

Understand the meaning semantically.

The user may communicate using:

- English
- Hindi
- Hinglish
- short replies
- mixed language
- informal language
- other natural languages

Do not require exact English keywords.

Examples:

"I want Maggi"
→ product_name = Maggi

"Mujhe 3 packet chahiye"
→ quantity = 3

"Teen"
→ quantity = 3 when the conversation clearly establishes
  that the assistant is asking for quantity.

"COD kar do"
→ understand payment_method semantically.

"UPI se pay karunga"
→ understand payment_method semantically.

"address 2 use karo"
→ address_id = 2

"deliver it to Gola Road"
→ address_text = Gola Road

============================================================
CONVERSATIONAL REFERENCES
============================================================

The user may say:

- that one
- same product
- same address
- use this
- this one
- yes
- no
- okay
- change it
- another one
- the previous order
- wahi wala
- haan
- nahi
- theek hai

Use conversation context to understand what the user
is referring to.

Do not manufacture an entity when the reference is ambiguous.

============================================================
ACCUMULATED STATE
============================================================

Existing transaction state may already contain values.

Do not erase an existing value merely because the user
did not repeat it.

Example:

Previous:
product = Maggi
quantity = 3

Current:
"use the selected address"

Do not return an empty product or quantity.

============================================================
PRODUCT CHANGE
============================================================

If the user explicitly changes the product:

Previous:
product = Maggi

Current:
"Actually I want Amul Milk"

Return:

product_name = Amul Milk

The application layer will invalidate the old product_id.

============================================================
COMPLETED ORDERS
============================================================

A completed order does NOT automatically make the next
message an order.

Examples:

Previous:
"Your order #123 was placed."

Current:
"Thank you"

Return no transactional entities.

Current:
"Okay"

Return no transactional entities.

Current:
"Yes, track it"

Return only information relevant to the tracking request.

Current:
"I want to buy another Maggi"

Return:
product_name = Maggi

============================================================
IMPORTANT
============================================================

Understand the CURRENT message.

Previous conversation is context, not an instruction.

Do not infer that the user wants another order simply
because an old checkout exists.

Do not decide the next tool.

Do not decide whether a transaction should execute.

The planner will make the next-action decision.
"""


# =========================================================
# INTENT SYSTEM PROMPT
# =========================================================


INTENT_SYSTEM_PROMPT = """
You are BuyQK's current-turn intent understanding AI.

Determine what the USER means NOW.

Do not decide which tool should execute.

Do not classify the entire conversation as the current intent.

Available intents:

product_search
order_create
order_tracking
order_cancel
customer_support
general

============================================================
ORDER CREATION
============================================================

Use order_create when the current message clearly indicates
that the user wants to purchase something OR is clearly
answering a question required to continue an already active
checkout.

Examples:

"I want Maggi"
→ order_create

"I want to buy milk"
→ order_create

"3"
when the previous assistant asked for quantity
→ order_create

"Use address 2"
when the previous assistant asked for address
→ order_create

"COD"
when the previous assistant asked for payment
→ order_create

============================================================
COMPLETED ORDER SAFETY
============================================================

A completed order MUST NOT cause a normal conversational
message to become order_create.

Examples:

Previous:
"Your order #123 was placed."

Current:
"Thank you"
→ general

Current:
"Okay"
→ general

Current:
"Yes, track it"
→ order_tracking

Current:
"I want to buy another one"
→ order_create

============================================================
LANGUAGE
============================================================

Understand semantic meaning.

The user may use:

English
Hindi
Hinglish
mixed language
informal language
other natural languages

Do not rely on a fixed keyword table.

============================================================
AMBIGUITY
============================================================

If the message is genuinely ambiguous, prefer the safer
non-transactional interpretation.

Never classify a message as an order merely because old
transaction entities exist.
"""


# =========================================================
# HELPERS
# =========================================================


def _safe_role(
    item: dict[str, Any],
) -> str:
    return str(
        item.get(
            "role",
            "",
        )
    ).strip().lower()


def _safe_content(
    item: dict[str, Any],
) -> str:
    return str(
        item.get(
            "content",
            "",
        )
    ).strip()


def _has_value(
    value: Any,
) -> bool:
    if value is None:
        return False

    if isinstance(
        value,
        str,
    ):
        return bool(
            value.strip()
        )

    return True


def _normalize_text(
    value: Any,
) -> Optional[str]:
    if value is None:
        return None

    text = str(
        value
    ).strip()

    return (
        text
        if text
        else None
    )


# =========================================================
# CONVERSATION FORMATTING
# =========================================================


def format_conversation_history(
    conversation_history: list[dict[str, Any]] | None,
) -> str:
    if not conversation_history:
        return "No previous conversation."

    lines: list[str] = []

    for item in conversation_history:

        role = _safe_role(item)
        content = _safe_content(item)

        if not content:
            continue

        lines.append(
            f"{role.upper()}: {content}"
        )

    if not lines:
        return "No previous conversation."

    return "\n".join(
        lines
    )


# =========================================================
# PREVIOUS ASSISTANT MESSAGE
# =========================================================


def get_previous_assistant_message(
    conversation_history: list[dict[str, Any]] | None,
) -> str:
    if not conversation_history:
        return ""

    for item in reversed(
        conversation_history
    ):

        role = _safe_role(item)

        if role in {
            "assistant",
            "ai",
        }:
            return _safe_content(
                item
            )

    return ""


# =========================================================
# NUMERIC QUANTITY SAFETY
# =========================================================
#
# This is deliberately limited.
#
# The LLM is responsible for semantic understanding.
#
# The deterministic layer only validates an unambiguous
# numeric quantity.
#
# =========================================================


def detect_quantity(
    message: str,
) -> Optional[int]:

    if not message:
        return None

    patterns = [
        r"\b(\d+)\s*(?:packets?|packs?|pieces?|pcs?|items?|units?)\b",
        r"\b(\d+)\s*(?:kg|kgs|kilograms?)\b",
        r"\b(\d+)\s*(?:g|grams?)\b",
        r"\b(?:quantity|qty)\s*(?:is|=|:)?\s*(\d+)\b",
        r"\bmake\s+it\s+(\d+)\b",
        r"\bchange\s+(?:it\s+)?to\s+(\d+)\b",
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            message,
            flags=re.IGNORECASE,
        )

        if not match:
            continue

        try:
            value = int(
                match.group(1)
            )

            if value > 0:
                return value

        except (
            TypeError,
            ValueError,
        ):
            continue

    # A plain number is only accepted when the AI intent
    # indicates that the message is a checkout continuation.
    return None


# =========================================================
# ADDRESS ID SAFETY
# =========================================================


def detect_address_id(
    message: str,
) -> Optional[int]:

    if not message:
        return None

    match = re.search(
        r"\baddress\s*(?:id)?\s*[:#]?\s*(\d+)\b",
        message,
        flags=re.IGNORECASE,
    )

    if not match:
        return None

    try:

        value = int(
            match.group(1)
        )

        return (
            value
            if value > 0
            else None
        )

    except (
        TypeError,
        ValueError,
    ):
        return None


# =========================================================
# ORDER ID SAFETY
# =========================================================


def detect_order_id(
    message: str,
) -> Optional[int]:

    if not message:
        return None

    match = re.search(
        r"\border\s*(?:id|number|no\.?)?\s*[:#]?\s*(\d+)\b",
        message,
        flags=re.IGNORECASE,
    )

    if not match:
        return None

    try:

        value = int(
            match.group(1)
        )

        return (
            value
            if value > 0
            else None
        )

    except (
        TypeError,
        ValueError,
    ):
        return None


# =========================================================
# AI ENTITY EXTRACTION
# =========================================================


def extract_entities(
    state: GraphState,
    message: str,
) -> LLMEntityOutput:

    if not message.strip():
        return LLMEntityOutput()

    history = (
        state.get(
            "conversation_history",
            [],
        )
        or []
    )

    existing_entities = (
        state.get(
            "entities",
            {},
        )
        or {}
    )

    context = f"""
CURRENT USER MESSAGE
====================
{message}

PREVIOUS CONVERSATION
=====================
{format_conversation_history(history)}

PREVIOUS ASSISTANT MESSAGE
==========================
{get_previous_assistant_message(history)}

CURRENT TRANSACTION STATE
=========================
{existing_entities}

CHECKOUT ID
===========
{state.get("checkout_id")}

CHECKOUT STATUS
===============
{state.get("checkout_status")}

ORDER CREATED
=============
{state.get("order_created")}

ORDER ID
========
{state.get("order_id")}

UNDERSTAND ONLY THE CURRENT MESSAGE.

Do not invent missing fields.

Do not calculate anything.

Do not create database identifiers.

Do not return product_id.
"""

    try:

        result = structured_entity_llm.invoke(
            [
                SystemMessage(
                    content=ENTITY_SYSTEM_PROMPT
                ),
                HumanMessage(
                    content=context
                ),
            ]
        )

        if isinstance(
            result,
            LLMEntityOutput,
        ):
            return result

    except Exception as exc:

        print(
            "[ENTITY LLM ERROR]"
            f" {type(exc).__name__}: {exc}"
        )

    return LLMEntityOutput()


# =========================================================
# AI CURRENT-TURN INTENT
# =========================================================


def resolve_current_turn_intent(
    state: GraphState,
    message: str,
) -> IntentDecision:

    history = (
        state.get(
            "conversation_history",
            [],
        )
        or []
    )

    context = f"""
CURRENT USER MESSAGE
====================
{message}

PREVIOUS CONVERSATION
=====================
{format_conversation_history(history)}

PREVIOUS ASSISTANT MESSAGE
==========================
{get_previous_assistant_message(history)}

CURRENT CHECKOUT ID
===================
{state.get("checkout_id")}

CHECKOUT STATUS
===============
{state.get("checkout_status")}

ORDER CREATED
=============
{state.get("order_created")}

ORDER ID
========
{state.get("order_id")}

CURRENT ENTITIES
================
{state.get("entities", {})}

Determine what the user means NOW.

Do not create a new order merely because previous
transaction entities exist.

Do not decide which backend tool should execute.
"""

    try:

        result = structured_intent_llm.invoke(
            [
                SystemMessage(
                    content=INTENT_SYSTEM_PROMPT
                ),
                HumanMessage(
                    content=context
                ),
            ]
        )

        if isinstance(
            result,
            IntentDecision,
        ):
            return result

    except Exception as exc:

        print(
            "[INTENT LLM ERROR]"
            f" {type(exc).__name__}: {exc}"
        )

    # Fail closed.
    return IntentDecision(
        intent="general",
        confidence=0.0,
    )


# =========================================================
# PRODUCT CHANGE DETECTION
# =========================================================


def _product_changed(
    previous_name: Any,
    current_name: Any,
) -> bool:

    previous = _normalize_text(
        previous_name
    )

    current = _normalize_text(
        current_name
    )

    if not previous or not current:
        return False

    return (
        previous.casefold()
        != current.casefold()
    )


# =========================================================
# CHECKOUT ID
# =========================================================


def _ensure_checkout_id(
    state: GraphState,
) -> str:

    existing = _normalize_text(
        state.get(
            "checkout_id"
        )
    )

    if existing:
        return existing

    return str(
        uuid.uuid4()
    )


# =========================================================
# START NEW CHECKOUT
# =========================================================


def _start_new_checkout(
    entities: dict[str, Any],
) -> dict[str, Any]:

    result = dict(
        entities
    )

    for key in (
        "product_id",
        "product_name",
        "quantity",
        "address_id",
        "address_text",
        "payment_method",
        "order_id",
    ):

        result.pop(
            key,
            None,
        )

    return result


# =========================================================
# MISSING FIELDS
# =========================================================


def get_missing_fields(
    intent: str,
    entities: dict[str, Any],
) -> list[str]:

    if intent == "product_search":

        if not _has_value(
            entities.get(
                "product_name"
            )
        ):
            return [
                "product_name"
            ]

        return []

    if intent == "order_create":

        if not _has_value(
            entities.get(
                "product_name"
            )
        ):
            return [
                "product_name"
            ]

        quantity = entities.get(
            "quantity"
        )

        if (
            quantity is None
            or not isinstance(
                quantity,
                int,
            )
            or quantity <= 0
        ):
            return [
                "quantity"
            ]

        if not _has_value(
            entities.get(
                "address_id"
            )
        ):
            return [
                "address_selection"
            ]

        if not _has_value(
            entities.get(
                "payment_method"
            )
        ):
            return [
                "payment_method"
            ]

        return []

    if intent == "order_tracking":

        if not _has_value(
            entities.get(
                "order_id"
            )
        ):
            return [
                "order_id"
            ]

        return []

    if intent == "order_cancel":

        if not _has_value(
            entities.get(
                "order_id"
            )
        ):
            return [
                "order_id"
            ]

        return []

    return []


# =========================================================
# ENTITY NORMALIZATION
# =========================================================


def _normalize_entities(
    entities: dict[str, Any],
) -> dict[str, Any]:

    result = dict(
        entities
    )

    # -----------------------------------------------------
    # Product name
    # -----------------------------------------------------

    if "product_name" in result:

        value = _normalize_text(
            result.get(
                "product_name"
            )
        )

        if value:
            result[
                "product_name"
            ] = value
        else:
            result.pop(
                "product_name",
                None,
            )

    # -----------------------------------------------------
    # Quantity
    # -----------------------------------------------------

    if result.get(
        "quantity"
    ) is not None:

        try:

            quantity = int(
                result[
                    "quantity"
                ]
            )

            if quantity > 0:
                result[
                    "quantity"
                ] = quantity
            else:
                result.pop(
                    "quantity",
                    None,
                )

        except (
            TypeError,
            ValueError,
        ):

            result.pop(
                "quantity",
                None,
            )

    # -----------------------------------------------------
    # Address ID
    # -----------------------------------------------------

    if result.get(
        "address_id"
    ) is not None:

        try:

            address_id = int(
                result[
                    "address_id"
                ]
            )

            if address_id > 0:
                result[
                    "address_id"
                ] = address_id
            else:
                result.pop(
                    "address_id",
                    None,
                )

        except (
            TypeError,
            ValueError,
        ):

            result.pop(
                "address_id",
                None,
            )

    # -----------------------------------------------------
    # Order ID
    # -----------------------------------------------------

    if result.get(
        "order_id"
    ) is not None:

        try:

            order_id = int(
                result[
                    "order_id"
                ]
            )

            if order_id > 0:
                result[
                    "order_id"
                ] = order_id
            else:
                result.pop(
                    "order_id",
                    None,
                )

        except (
            TypeError,
            ValueError,
        ):

            result.pop(
                "order_id",
                None,
            )

    # -----------------------------------------------------
    # Address text
    # -----------------------------------------------------

    if "address_text" in result:

        address_text = _normalize_text(
            result.get(
                "address_text"
            )
        )

        if address_text:
            result[
                "address_text"
            ] = address_text
        else:
            result.pop(
                "address_text",
                None,
            )

    # -----------------------------------------------------
    # Payment
    # -----------------------------------------------------
    #
    # The AI performs semantic interpretation.
    #
    # This layer only normalizes representation.
    #
    # Backend remains authoritative for payment validity.
    # -----------------------------------------------------

    if result.get(
        "payment_method"
    ) is not None:

        payment = _normalize_text(
            result.get(
                "payment_method"
            )
        )

        if payment:
            result[
                "payment_method"
            ] = payment.casefold()
        else:
            result.pop(
                "payment_method",
                None,
            )

    return result


# =========================================================
# ENTITY NODE
# =========================================================


def entity_node(
    state: GraphState,
) -> GraphState:

    message = (
        state.get(
            "message",
            "",
        )
        or ""
    ).strip()

    existing_entities = dict(
        state.get(
            "entities",
            {},
        )
        or {}
    )

    original_intent = state.get(
        "intent",
        "general",
    )

    # =====================================================
    # 1. CURRENT-TURN AI UNDERSTANDING
    # =====================================================

    intent_decision = (
        resolve_current_turn_intent(
            state=state,
            message=message,
        )
    )

    current_intent = (
        intent_decision.intent
    )

    confidence = (
        intent_decision.confidence
    )

    # =====================================================
    # 2. EXTRACT CURRENT-TURN ENTITIES
    # =====================================================

    extracted = extract_entities(
        state=state,
        message=message,
    )

    extracted_entities = (
        extracted.model_dump(
            exclude_none=True
        )
    )

    # Keep the current-turn understanding separately.
    #
    # This is important for Phase 2 because the planner can
    # inspect what the user said NOW without confusing it
    # with accumulated transaction state.

    current_turn_entities = dict(
        extracted_entities
    )

    # =====================================================
    # 3. MERGE ACCUMULATED STATE
    # =====================================================
    #
    # Existing values survive unless the current AI
    # understanding explicitly changes them.
    #
    # =====================================================

    entities = dict(
        existing_entities
    )

    for key, value in extracted_entities.items():

        if value is not None:
            entities[key] = value

    # =====================================================
    # 4. NUMERIC QUANTITY VALIDATION
    # =====================================================
    #
    # Only accept an unambiguous numeric quantity.
    #
    # We deliberately do NOT treat every plain number as a
    # quantity. That prevents:
    #
    # "show order 123"
    #
    # from becoming quantity=123.
    #
    # The AI entity extraction remains responsible for
    # semantic quantity understanding.
    #
    # =====================================================

    explicit_quantity = detect_quantity(
        message
    )

    if explicit_quantity is not None:

        entities[
            "quantity"
        ] = explicit_quantity

        current_turn_entities[
            "quantity"
        ] = explicit_quantity

    # =====================================================
    # 5. ADDRESS ID SAFETY
    # =====================================================

    explicit_address_id = (
        detect_address_id(
            message
        )
    )

    if explicit_address_id is not None:

        entities[
            "address_id"
        ] = explicit_address_id

        current_turn_entities[
            "address_id"
        ] = explicit_address_id

        entities.pop(
            "address_text",
            None,
        )

    # =====================================================
    # 6. ORDER ID SAFETY
    # =====================================================

    explicit_order_id = (
        detect_order_id(
            message
        )
    )

    if explicit_order_id is not None:

        entities[
            "order_id"
        ] = explicit_order_id

        current_turn_entities[
            "order_id"
        ] = explicit_order_id

    # =====================================================
    # 7. FRONTEND ADDRESS SELECTION
    # =====================================================
    #
    # Frontend selection is authoritative.
    #
    # The LLM cannot override it.
    #
    # =====================================================

    selected_address_id = state.get(
        "selected_address_id"
    )

    if selected_address_id is not None:

        try:

            normalized_address_id = int(
                selected_address_id
            )

            if normalized_address_id > 0:

                entities[
                    "address_id"
                ] = normalized_address_id

                entities.pop(
                    "address_text",
                    None,
                )

        except (
            TypeError,
            ValueError,
        ):

            print(
                "[ENTITY] Invalid selected_address_id:",
                repr(
                    selected_address_id
                ),
            )

    # =====================================================
    # 8. FRONTEND PAYMENT SELECTION
    # =====================================================
    #
    # Frontend selection is authoritative for what the user
    # selected.
    #
    # Backend remains authoritative for whether that payment
    # method is valid/available.
    #
    # =====================================================

    selected_payment_method = (
        state.get(
            "selected_payment_method"
        )
    )

    if not selected_payment_method:

        selected_payment_method = (
            state.get(
                "payment_method"
            )
        )

    if selected_payment_method:

        payment = _normalize_text(
            selected_payment_method
        )

        if payment:

            entities[
                "payment_method"
            ] = payment.casefold()

    # =====================================================
    # 9. PRODUCT CONSISTENCY
    # =====================================================
    #
    # product_id is backend-authoritative.
    #
    # If the user changes product_name, the old product_id
    # cannot continue to represent the new product.
    #
    # =====================================================

    previous_product_name = (
        existing_entities.get(
            "product_name"
        )
    )

    previous_product_id = (
        existing_entities.get(
            "product_id"
        )
    )

    current_product_name = (
        entities.get(
            "product_name"
        )
    )

    product_changed = (
        _product_changed(
            previous_product_name,
            current_product_name,
        )
    )

    if product_changed:

        entities.pop(
            "product_id",
            None,
        )

    elif previous_product_id is not None:

        try:

            normalized_product_id = int(
                previous_product_id
            )

            if normalized_product_id > 0:

                entities[
                    "product_id"
                ] = normalized_product_id

        except (
            TypeError,
            ValueError,
        ):

            entities.pop(
                "product_id",
                None,
            )

    # =====================================================
    # 10. PRODUCT ID SAFETY
    # =====================================================
    #
    # Entity node never creates product IDs.
    #
    # It may preserve an already backend-resolved product ID.
    #
    # =====================================================

    if entities.get(
        "product_id"
    ) is not None:

        try:

            product_id = int(
                entities[
                    "product_id"
                ]
            )

            if product_id > 0:

                entities[
                    "product_id"
                ] = product_id

            else:

                entities.pop(
                    "product_id",
                    None,
                )

        except (
            TypeError,
            ValueError,
        ):

            entities.pop(
                "product_id",
                None,
            )

    # =====================================================
    # 11. NORMALIZE ENTITIES
    # =====================================================

    entities = _normalize_entities(
        entities
    )

    # =====================================================
    # 12. PRODUCT NAME SAFETY
    # =====================================================

    product_name = _normalize_text(
        entities.get(
            "product_name"
        )
    )

    if product_name:

        entities[
            "product_name"
        ] = product_name

    else:

        entities.pop(
            "product_name",
            None,
        )

        # Never preserve a product ID when the corresponding
        # natural-language product is no longer present.

        entities.pop(
            "product_id",
            None,
        )

    # =====================================================
    # 13. ORDER ID
    # =====================================================
    #
    # Preserve a previously established order ID only when
    # the user is talking about an existing order.
    #
    # This does NOT create an order.
    #
    # =====================================================

    order_id = entities.get(
        "order_id"
    )

    previous_order_id = state.get(
        "order_id"
    )

    if (
        order_id is None
        and previous_order_id is not None
        and current_intent
        in {
            "order_tracking",
            "order_cancel",
        }
    ):

        try:

            normalized_order_id = int(
                previous_order_id
            )

            if normalized_order_id > 0:

                order_id = (
                    normalized_order_id
                )

                entities[
                    "order_id"
                ] = order_id

        except (
            TypeError,
            ValueError,
        ):
            pass

    # =====================================================
    # 14. AUTHORITATIVE TRANSACTION STATE
    # =====================================================

    previous_checkout_id = (
        state.get(
            "checkout_id"
        )
    )

    previous_checkout_status = (
        state.get(
            "checkout_status"
        )
    )

    previous_order_created = bool(
        state.get(
            "order_created",
            False,
        )
    )

    # -----------------------------------------------------
    # DO NOT CREATE A NEW CHECKOUT HERE
    # -----------------------------------------------------
    #
    # This is a major Phase 2 architectural change.
    #
    # Entity node should understand the message.
    #
    # Planner decides whether it represents:
    #
    #   new order
    #   continuation
    #   modification
    #   tracking
    #   support
    #   general conversation
    #
    # We therefore preserve the existing checkout ID.
    #
    # If a checkout does not yet exist, the planner/backend
    # transaction layer can establish one when appropriate.
    #
    # -----------------------------------------------------

    checkout_id = _normalize_text(
        previous_checkout_id
    )

    checkout_status = (
        previous_checkout_status
    )

    order_created = (
        previous_order_created
    )

    # =====================================================
    # 15. COMPLETED ORDER PRESERVATION
    # =====================================================
    #
    # A completed transaction remains completed.
    #
    # "Thank you"
    # "Okay"
    # "Thanks"
    #
    # must not erase the transaction.
    #
    # But this node also must not reinterpret those messages
    # as a new order.
    #
    # =====================================================

    if order_created:

        if not checkout_status:

            checkout_status = (
                "completed"
            )

    # =====================================================
    # 16. CHECKOUT STATE MIRRORS
    # =====================================================
    #
    # These are mirrors of accumulated understanding.
    #
    # They are NOT backend confirmation that an order exists.
    #
    # =====================================================

    product_id = entities.get(
        "product_id"
    )

    quantity = entities.get(
        "quantity"
    )

    address_id = entities.get(
        "address_id"
    )

    payment_method = entities.get(
        "payment_method"
    )

    # =====================================================
    # 17. MISSING FIELDS
    # =====================================================
    #
    # This is a state completeness calculation, not a tool
    # decision.
    #
    # Planner decides whether those fields should actually be
    # requested from the user.
    #
    # =====================================================

    missing_fields = (
        get_missing_fields(
            intent=current_intent,
            entities=entities,
        )
    )

    # =====================================================
    # 18. BILL PRESERVATION
    # =====================================================
    #
    # Entity node never calculates or modifies billing.
    #
    # Backend-generated bill remains authoritative.
    #
    # =====================================================

    billing = state.get(
        "billing"
    )

    bill = state.get(
        "bill"
    )

    billing_items = state.get(
        "billing_items"
    )

    subtotal = state.get(
        "subtotal"
    )

    delivery_charge = state.get(
        "delivery_charge"
    )

    discount = state.get(
        "discount"
    )

    tax = state.get(
        "tax"
    )

    total_amount = state.get(
        "total_amount"
    )

    currency = state.get(
        "currency"
    )

    billing_payment_method = state.get(
        "billing_payment_method"
    )

    # =====================================================
    # 19. AI UNDERSTANDING CONTRACT
    # =====================================================
    #
    # Planner receives a clean current-turn understanding.
    #
    # The planner should use this object to determine the
    # next conversational action.
    #
    # =====================================================

    understanding = {
        "intent": current_intent,
        "confidence": confidence,
        "message": message,
        "current_turn_entities": (
            current_turn_entities
        ),
        "accumulated_entities": dict(
            entities
        ),
        "missing_fields": list(
            missing_fields
        ),
        "checkout_id": checkout_id,
        "checkout_status": checkout_status,
        "order_created": order_created,
        "order_id": order_id,
    }

    # =====================================================
    # 20. DEBUG
    # =====================================================

    print(
        "\n"
        "====================================================\n"
        "[ENTITY / UNDERSTANDING NODE]\n"
        "====================================================\n"
        f"message          = {message!r}\n"
        f"intent_before    = {original_intent!r}\n"
        f"intent_after     = {current_intent!r}\n"
        f"confidence       = {confidence!r}\n"
        f"checkout_id      = {checkout_id!r}\n"
        f"checkout_status  = {checkout_status!r}\n"
        f"order_created    = {order_created}\n"
        f"order_id         = {order_id!r}\n"
        f"product_id       = {product_id!r}\n"
        f"product_name     = {product_name!r}\n"
        f"quantity         = {quantity!r}\n"
        f"address_id       = {address_id!r}\n"
        f"payment_method   = {payment_method!r}\n"
        f"missing_fields   = {missing_fields!r}\n"
        f"current_turn     = {current_turn_entities!r}\n"
        f"entities         = {entities!r}\n"
        "====================================================\n"
    )

    # =====================================================
    # 21. GRAPH STATE UPDATE
    # =====================================================

    result: GraphState = {
        # -------------------------------------------------
        # Current-turn understanding
        # -------------------------------------------------

        "intent": current_intent,

        "entities": entities,

        "missing_fields": missing_fields,

        # -------------------------------------------------
        # Authoritative checkout state
        # -------------------------------------------------

        "checkout_id": checkout_id,

        "checkout_status": checkout_status,

        "order_created": order_created,

        "order_id": order_id,

        # -------------------------------------------------
        # Transaction entities
        # -------------------------------------------------

        "product_id": product_id,

        "product_name": product_name,

        "quantity": quantity,

        "address_id": address_id,

        "selected_payment_method": (
            payment_method
        ),

        # Backward compatibility.
        "payment_method": payment_method,

        # -------------------------------------------------
        # Phase 2 understanding contract
        # -------------------------------------------------

        "current_turn_entities": (
            current_turn_entities
        ),

        "understanding": understanding,
    }

    # =====================================================
    # 22. PRESERVE AUTHORITATIVE BILLING
    # =====================================================

    if billing is not None:
        result[
            "billing"
        ] = billing

    if bill is not None:
        result[
            "bill"
        ] = bill

    if billing_items is not None:
        result[
            "billing_items"
        ] = billing_items

    if subtotal is not None:
        result[
            "subtotal"
        ] = subtotal

    if delivery_charge is not None:
        result[
            "delivery_charge"
        ] = delivery_charge

    if discount is not None:
        result[
            "discount"
        ] = discount

    if tax is not None:
        result[
            "tax"
        ] = tax

    if total_amount is not None:
        result[
            "total_amount"
        ] = total_amount

    if currency is not None:
        result[
            "currency"
        ] = currency

    if billing_payment_method is not None:
        result[
            "billing_payment_method"
        ] = billing_payment_method

    return result


# =========================================================
# COMPATIBILITY HELPERS
# =========================================================
#
# These functions remain so older imports do not immediately
# break.
#
# IMPORTANT:
#
# They no longer make transactional decisions.
# =========================================================


def resolve_transaction_intent(
    state: GraphState,
    entities: dict[str, Any],
    message: str,
) -> str:

    return resolve_current_turn_intent(
        state=state,
        message=message,
    ).intent


def _is_new_order_request(
    message: str,
) -> bool:
    """
    Deprecated.

    New-order planning belongs to planner_node.py.
    """

    return False


def _is_explicit_tracking_request(
    message: str,
) -> bool:
    """
    Deprecated.

    Tracking decisions belong to planner_node.py.
    """

    return False


def _is_explicit_cancel_request(
    message: str,
) -> bool:
    """
    Deprecated.

    Cancellation decisions belong to planner_node.py.
    """

    return False


def _is_explicit_support_request(
    message: str,
) -> bool:
    """
    Deprecated.

    Support decisions belong to planner_node.py.
    """

    return False


def _is_payment_selection(
    message: str,
) -> bool:
    """
    Compatibility helper.

    Payment interpretation is performed by the AI.
    """

    return bool(
        message
        and message.strip()
    )


def _is_address_selection(
    state: GraphState,
    message: str,
) -> bool:
    """
    Compatibility helper.

    Frontend selection is authoritative.
    """

    if state.get(
        "selected_address_id"
    ) is not None:

        return True

    return (
        detect_address_id(
            message
        )
        is not None
    )


def _is_active_order_checkout(
    state: GraphState,
    entities: dict[str, Any],
    message: str,
) -> bool:
    """
    Compatibility helper.

    Active checkout is based on authoritative transaction
    state rather than merely the presence of old entities.
    """

    checkout_status = state.get(
        "checkout_status"
    )

    if checkout_status in {
        "collecting",
        "ready",
    }:
        return True

    return (
        state.get(
            "intent"
        )
        == "order_create"
        and not state.get(
            "order_created",
            False,
        )
    )