# =========================================================
# BuyQK AI - Entity Node
# =========================================================
#
# Purpose:
# Context-aware structured entity extraction and
# transaction-state reconstruction for BuyQK AI.
#
# Main responsibility:
#
#   Conversation History
#          ↓
#   Current User Message
#          ↓
#   LLM Extraction
#          ↓
#   Deterministic Extraction
#          ↓
#   Previous User-Turn Recovery
#          ↓
#   Existing Graph Entity Merge
#          ↓
#   Frontend Selection Merge
#          ↓
#   Intent Resolution
#          ↓
#   Missing Field Detection
#
# Critical checkout flow:
#
#   Product
#      ↓
#   Quantity
#      ↓
#   Address
#      ↓
#   Payment
#      ↓
#   Create Order
#
# IMPORTANT:
# This node DOES NOT execute backend tools.
#
# =========================================================


from __future__ import annotations

import re
from typing import Any, Optional

from pydantic import BaseModel, Field

from langchain_core.messages import (
    HumanMessage,
    SystemMessage,
)

from ai_engine.graph.state import GraphState
from ai_engine.llm.client import get_llm


# =========================================================
# Structured Entity Output
# =========================================================


class EntityOutput(BaseModel):
    """
    Complete structured checkout entity state.

    product_id is backend-authoritative. It may be preserved from
    graph state or written by a backend/tool node, but it must never
    be generated by the LLM.
    """

    # -----------------------------------------------------
    # Product
    # -----------------------------------------------------

    product_id: Optional[int] = Field(
        default=None,
        ge=1,
        description=(
            "Authoritative database product ID. "
            "Must come from backend/database state; "
            "never infer or invent it."
        ),
    )

    product_name: Optional[str] = Field(
        default=None,
        description=(
            "Natural-language or display name of the "
            "product currently being ordered."
        ),
    )

    # -----------------------------------------------------
    # Quantity
    # -----------------------------------------------------

    quantity: Optional[int] = Field(
        default=None,
        ge=1,
        description="Requested positive quantity.",
    )

    # -----------------------------------------------------
    # Order
    # -----------------------------------------------------

    order_id: Optional[int] = Field(
        default=None,
        ge=1,
        description="Order ID currently being discussed.",
    )

    # -----------------------------------------------------
    # Address
    # -----------------------------------------------------

    address_id: Optional[int] = Field(
        default=None,
        ge=1,
        description="Saved delivery address ID.",
    )

    address_text: Optional[str] = Field(
        default=None,
        description="Natural-language delivery address.",
    )

    # -----------------------------------------------------
    # Payment
    # -----------------------------------------------------

    payment_method: Optional[str] = Field(
        default=None,
        description="Supported payment method: upi or cod.",
    )


class LLMEntityOutput(BaseModel):
    """
    Fields the LLM is allowed to extract.

    IMPORTANT: product_id is deliberately absent. Product IDs are
    database identifiers and must never be hallucinated by the LLM.
    """

    product_name: Optional[str] = Field(
        default=None,
        description="Product name mentioned or implied by the user.",
    )

    quantity: Optional[int] = Field(
        default=None,
        ge=1,
        description="Explicit positive quantity supplied by the user.",
    )

    order_id: Optional[int] = Field(
        default=None,
        ge=1,
        description="Order ID explicitly supplied or referenced by the user.",
    )

    address_id: Optional[int] = Field(
        default=None,
        ge=1,
        description="Saved address ID explicitly selected by the user.",
    )

    address_text: Optional[str] = Field(
        default=None,
        description="Natural-language delivery address supplied by the user.",
    )

    payment_method: Optional[str] = Field(
        default=None,
        description="Payment method: upi or cod.",
    )


# =========================================================
# LLM Prompt
# =========================================================


ENTITY_SYSTEM_PROMPT = """
You are the entity and checkout-state resolution component
of BuyQK AI.

Your job is to return the COMPLETE CURRENT ENTITY STATE.

Supported fields:

- product_name
- quantity
- order_id
- address_id
- address_text
- payment_method

product_id is NOT an LLM-extracted field. Never invent, infer,
or change a product_id. It must come only from backend/database
state after product resolution.


=========================================================
CRITICAL ACCUMULATION RULE
=========================================================

Never erase a previously established entity merely because
it is absent from the current message.

The current state is:

previous state
+
conversation history
+
current user message


Example:

User:
"I want to order Amul milk"

Assistant:
"How much Amul milk would you like?"

User:
"3 packets"

Assistant:
"Please choose your delivery address."

User:
"Use the selected delivery address."

The final entity state MUST remain:

product_name = "Amul milk"
quantity = 3

If a backend-resolved product_id already exists, preserve it
unless the user explicitly changes the product.

The address selection must NOT erase quantity.


=========================================================
CHECKOUT CONTINUITY
=========================================================

The following messages are normally continuations of the
same order:

- "3 packets"
- "2 kg"
- "Home"
- "Use the selected delivery address"
- "address 2"
- "UPI"
- "COD"
- "Cash on delivery"
- "Selected payment method: COD"

Do not classify these as support requests.


=========================================================
QUANTITY
=========================================================

Only return a quantity when the user explicitly provides one.

Examples:

"3 packets" → quantity = 3

"2 kg" → quantity = 2

"quantity 5" → quantity = 5

"make it 4" → quantity = 4

Do NOT assume quantity = 1.


=========================================================
ADDRESS
=========================================================

A saved address ID belongs in address_id.

Example:

"address 12" → address_id = 12

A natural-language address belongs in address_text.

Example:

"My address is Gola Road, Patna"
→ address_text = "Gola Road, Patna"


=========================================================
PAYMENT
=========================================================

Supported methods:

upi
cod

Examples:

"UPI" → upi

"I want to pay by UPI" → upi

"COD" → cod

"Cash on delivery" → cod

Never invent a payment method.


=========================================================
PRODUCT
=========================================================

Preserve the previously selected product during checkout.

If the user explicitly changes the product, update it.

Example:

Previous:
product_name = "Amul milk"
product_id = 15

Current:
"Actually I want bread instead"

Return:

product_name = "bread"

The backend/entity merge layer must clear the old product_id
because it belongs to Amul milk, not bread.


=========================================================
IMPORTANT
=========================================================

Return the COMPLETE accumulated state.

Do not return only newly discovered fields.
"""


# =========================================================
# LLM Setup
# =========================================================


llm = get_llm()

structured_llm = llm.with_structured_output(
    LLMEntityOutput
)


# =========================================================
# Conversation Helpers
# =========================================================


def _safe_role(item: dict[str, Any]) -> str:
    return str(
        item.get("role", "")
    ).strip().lower()


def _safe_content(item: dict[str, Any]) -> str:
    return str(
        item.get("content", "")
    ).strip()


def format_conversation_history(
    conversation_history: list[dict[str, Any]] | None,
) -> str:
    """
    Format conversation history for the LLM.
    """

    if not conversation_history:
        return "No previous conversation."

    lines: list[str] = []

    for item in conversation_history:

        role = _safe_role(item)

        content = _safe_content(item)

        if not content:
            continue

        lines.append(
            f"{role.upper()}: {content}"
        )

    if not lines:
        return "No previous conversation."

    return "\n".join(lines)


def get_user_history(
    conversation_history: list[dict[str, Any]] | None,
) -> list[tuple[int, str]]:
    """
    Return only user messages.

    This is extremely important.

    We should NOT recover quantities from assistant messages,
    because assistant messages may contain questions such as:

        "How much would you like?"

    or examples containing numbers.
    """

    result: list[tuple[int, str]] = []

    if not conversation_history:
        return result

    for index, item in enumerate(
        conversation_history
    ):

        role = _safe_role(item)

        content = _safe_content(item)

        if role in {
            "user",
            "human",
        } and content:

            result.append(
                (index, content)
            )

    return result


def get_previous_assistant_message(
    conversation_history: list[dict[str, Any]] | None,
    user_index: int,
) -> str:
    """
    Find the assistant message immediately preceding
    a particular user message.
    """

    if not conversation_history:
        return ""

    for index in range(
        user_index - 1,
        -1,
        -1,
    ):

        item = conversation_history[index]

        role = _safe_role(item)

        if role in {
            "assistant",
            "ai",
        }:

            return _safe_content(item)

    return ""


# =========================================================
# Basic Helpers
# =========================================================


def _has_value(
    value: Any,
) -> bool:
    if value is None:
        return False

    if isinstance(value, str):
        return bool(value.strip())

    return True


def _normalize_text(
    value: Any,
) -> Optional[str]:

    if value is None:
        return None

    text = str(value).strip()

    return text if text else None


# =========================================================
# Quantity Detection
# =========================================================


def detect_quantity(
    message: str,
    allow_plain_number: bool = True,
) -> Optional[int]:
    """
    Detect explicit quantity from a message.

    Examples:

        3 packets
        2 kg
        quantity 4
        qty = 5
        make it 6
        change it to 7
        want 3

    Plain numbers are supported for direct user replies:

        3
        5
    """

    if not message:
        return None

    patterns = [
        # 3 packets
        r"\b(\d+)\s*(?:packets?|packs?|pieces?|pcs?|items?|units?)\b",

        # 3 kg / 3 kilograms
        r"\b(\d+)\s*(?:kg|kgs|kilograms?)\b",

        # 3 grams
        r"\b(\d+)\s*(?:g|grams?)\b",

        # quantity 3
        r"\b(?:quantity|qty)\s*(?:is|=|:)?\s*(\d+)\b",

        # make it 5
        r"\bmake\s+it\s+(\d+)\b",

        # change it to 5
        r"\bchange\s+(?:it\s+)?to\s+(\d+)\b",

        # want 3
        r"\b(?:want|need|like)\s+(\d+)\b",
    ]

    if allow_plain_number:
        patterns.append(
            r"^\s*(\d+)\s*$"
        )

    for pattern in patterns:

        match = re.search(
            pattern,
            message,
            flags=re.IGNORECASE,
        )

        if not match:
            continue

        try:

            value = int(
                match.group(1)
            )

            if value > 0:
                return value

        except (
            TypeError,
            ValueError,
        ):
            continue

    return None


# =========================================================
# Recover Quantity From Previous User Turns
# =========================================================


def recover_quantity_from_history(
    conversation_history: list[dict[str, Any]] | None,
) -> Optional[int]:
    """
    Recover the latest quantity supplied by the USER.

    This fixes the main bug:

        User: I want Amul milk
        Assistant: How much?
        User: 3 packets
        Assistant: Choose address
        User: Use selected address

    On the final turn, the current message contains no
    quantity. Therefore quantity must be recovered from
    the earlier user turn.
    """

    user_messages = get_user_history(
        conversation_history
    )

    if not user_messages:
        return None

    # -----------------------------------------------------
    # First pass:
    # Strong quantity expressions.
    # -----------------------------------------------------

    for _, content in reversed(
        user_messages
    ):

        value = detect_quantity(
            content,
            allow_plain_number=False,
        )

        if value is not None:
            return value

    # -----------------------------------------------------
    # Second pass:
    # A plain numeric answer is valid when the assistant
    # immediately before it asked for quantity.
    # -----------------------------------------------------

    for index, content in reversed(
        user_messages
    ):

        if not re.fullmatch(
            r"\s*\d+\s*",
            content,
        ):
            continue

        assistant_message = (
            get_previous_assistant_message(
                conversation_history,
                index,
            )
            .lower()
        )

        quantity_question = any(
            phrase in assistant_message
            for phrase in (
                "how much",
                "how many",
                "quantity",
                "how many packets",
                "how many pieces",
                "how many items",
                "what quantity",
            )
        )

        if not quantity_question:
            continue

        value = detect_quantity(
            content,
            allow_plain_number=True,
        )

        if value is not None:
            return value

    return None


# =========================================================
# Address Text Detection
# =========================================================


def detect_address_text(
    message: str,
) -> Optional[str]:

    if not message:
        return None

    patterns = [
        r"(?:my\s+)?(?:delivery\s+)?address\s+(?:is|:)\s*(.+)",

        r"(?:deliver|delivery)\s+(?:it\s+)?to\s+(.+)",

        r"(?:send|ship)\s+(?:it\s+)?to\s+(.+)",
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            message,
            flags=re.IGNORECASE,
        )

        if not match:
            continue

        value = (
            match.group(1)
            .strip()
            .rstrip(".")
        )

        if value:
            return value

    return None


# =========================================================
# Address ID Detection
# =========================================================


def detect_address_id(
    message: str,
) -> Optional[int]:

    if not message:
        return None

    match = re.search(
        r"\baddress\s*(?:id)?\s*[:#]?\s*(\d+)\b",
        message,
        flags=re.IGNORECASE,
    )

    if not match:
        return None

    try:

        value = int(
            match.group(1)
        )

        return (
            value
            if value > 0
            else None
        )

    except ValueError:

        return None


# =========================================================
# Order ID Detection
# =========================================================


def detect_order_id(
    message: str,
) -> Optional[int]:

    if not message:
        return None

    match = re.search(
        r"\border\s*(?:id|number|no\.?)?\s*[:#]?\s*(\d+)\b",
        message,
        flags=re.IGNORECASE,
    )

    if not match:
        return None

    try:

        value = int(
            match.group(1)
        )

        return (
            value
            if value > 0
            else None
        )

    except ValueError:

        return None


# =========================================================
# Payment Detection
# =========================================================


def detect_payment_method(
    message: str,
) -> Optional[str]:

    if not message:
        return None

    text = (
        message
        .strip()
        .lower()
    )

    # UPI
    if re.search(
        r"\bupi\b",
        text,
    ):
        return "upi"

    # COD
    if (
        "cash on delivery" in text
        or re.search(
            r"\bcod\b",
            text,
        )
    ):
        return "cod"

    return None


# =========================================================
# Recover Payment From User History
# =========================================================


def recover_payment_from_history(
    conversation_history: list[dict[str, Any]] | None,
) -> Optional[str]:

    user_messages = get_user_history(
        conversation_history
    )

    for _, content in reversed(
        user_messages
    ):

        payment = detect_payment_method(
            content
        )

        if payment:
            return payment

    return None


# =========================================================
# Recover Address ID From User History
# =========================================================


def recover_address_id_from_history(
    conversation_history: list[dict[str, Any]] | None,
) -> Optional[int]:

    user_messages = get_user_history(
        conversation_history
    )

    for _, content in reversed(
        user_messages
    ):

        address_id = detect_address_id(
            content
        )

        if address_id is not None:
            return address_id

    return None


# =========================================================
# Recover Order ID From User History
# =========================================================


def recover_order_id_from_history(
    conversation_history: list[dict[str, Any]] | None,
) -> Optional[int]:

    user_messages = get_user_history(
        conversation_history
    )

    for _, content in reversed(
        user_messages
    ):

        order_id = detect_order_id(
            content
        )

        if order_id is not None:
            return order_id

    return None


# =========================================================
# Product Fallback
# =========================================================


def detect_product_fallback(
    message: str,
    conversation_history: list[dict[str, Any]] | None,
) -> Optional[str]:
    """
    Conservative product-name fallback for short checkout turns.

    This function does NOT resolve a product ID and does not query
    the database. It only tries to recover a product name from an
    earlier user order/buy request when the LLM did not return one.
    """

    # If the current message is a quantity/address/payment continuation,
    # recover the product from an earlier user order statement.
    user_messages = get_user_history(
        conversation_history
    )

    if not user_messages:
        return None

    # Do not treat a current explicit product-like request as a fallback
    # when it is actually just a quantity/payment/address continuation.
    continuation_only = (
        detect_quantity(message) is not None
        or detect_payment_method(message) is not None
        or detect_address_id(message) is not None
        or bool(detect_address_text(message))
        or bool(re.fullmatch(
            r"\s*(?:home|work|office|selected(?:\s+delivery)?\s+address|use\s+(?:the\s+)?selected\s+address)\s*",
            message or "",
            flags=re.IGNORECASE,
        ))
    )

    if not continuation_only:
        return None

    patterns = (
        r"\bi\s+(?:want|need)\s+to\s+(?:order|buy|get)\s+(.+?)\s*$",
        r"\bi\s+(?:want|need)\s+(?:to\s+)?(?:order|buy|get)\s+(.+?)\s*$",
        r"\bi(?:'d|\s+would)\s+like\s+to\s+(?:order|buy|get)\s+(.+?)\s*$",
        r"\b(?:order|buy|get|purchase)\s+(.+?)\s*$",
    )

    for _, content in reversed(user_messages):
        if detect_quantity(content, allow_plain_number=False) is not None:
            # A quantity-only message is not a product statement.
            continue

        for pattern in patterns:
            match = re.search(
                pattern,
                content,
                flags=re.IGNORECASE,
            )

            if not match:
                continue

            candidate = (
                match.group(1)
                .strip()
                .rstrip(".!?,")
            )

            if not candidate:
                continue

            if detect_quantity(candidate) is not None:
                continue

            if detect_payment_method(candidate) is not None:
                continue

            return candidate

    return None


# =========================================================
# New Order Detection
# =========================================================


def _is_new_order_request(
    message: str,
) -> bool:
    """
    Detect an explicit request to start a new order.

    This prevents stale checkout information from an
    earlier completed order being reused.
    """

    if not message:
        return False

    text = (
        message
        .strip()
        .lower()
    )

    continuation_phrases = (
        "actually",
        "instead",
        "change it",
        "make it",
        "change the product",
    )

    if any(
        phrase in text
        for phrase in continuation_phrases
    ):
        return False

    new_order_patterns = (
        r"\bi\s+want\s+to\s+order\b",
        r"\bi'd\s+like\s+to\s+order\b",
        r"\bi\s+would\s+like\s+to\s+order\b",
        r"\bi\s+want\s+to\s+buy\b",
        r"\bi'd\s+like\s+to\s+buy\b",
        r"\bplace\s+(?:an\s+)?order\b",
        r"\bnew\s+order\b",
    )

    return any(
        re.search(
            pattern,
            text,
            flags=re.IGNORECASE,
        )
        for pattern in new_order_patterns
    )


# =========================================================
# Explicit Tracking
# =========================================================


def _is_explicit_tracking_request(
    message: str,
) -> bool:

    phrases = (
        "track my order",
        "track order",
        "track my delivery",
        "where is my order",
        "where's my order",
        "where is my delivery",
        "order status",
        "delivery status",
        "check my order",
        "check order status",
    )

    text = (
        message or ""
    ).lower()

    return any(
        phrase in text
        for phrase in phrases
    )


# =========================================================
# Explicit Cancellation
# =========================================================


def _is_explicit_cancel_request(
    message: str,
) -> bool:

    phrases = (
        "cancel my order",
        "cancel order",
        "i want to cancel",
        "please cancel",
        "cancel it",
    )

    text = (
        message or ""
    ).lower()

    return any(
        phrase in text
        for phrase in phrases
    )


# =========================================================
# Explicit Support
# =========================================================


def _is_explicit_support_request(
    message: str,
) -> bool:

    phrases = (
        "contact support",
        "talk to support",
        "customer support",
        "raise a complaint",
        "file a complaint",
        "create a ticket",
        "support ticket",
        "i have a problem",
        "i have an issue",
    )

    text = (
        message or ""
    ).lower()

    return any(
        phrase in text
        for phrase in phrases
    )


# =========================================================
# Payment Selection
# =========================================================


def _is_payment_selection(
    message: str,
) -> bool:

    return (
        detect_payment_method(
            message
        )
        is not None
    )


# =========================================================
# Address Selection
# =========================================================


def _is_address_selection(
    state: GraphState,
    message: str,
) -> bool:

    if (
        state.get(
            "selected_address_id"
        )
        is not None
    ):
        return True

    if (
        detect_address_id(
            message
        )
        is not None
    ):
        return True

    text = (
        message or ""
    ).lower()

    return any(
        phrase in text
        for phrase in (
            "selected delivery address",
            "use the selected address",
            "use selected address",
            "use this address",
            "address selected",
        )
    )


# =========================================================
# Active Checkout Detection
# =========================================================


def _is_active_order_checkout(
    state: GraphState,
    entities: dict[str, Any],
    message: str,
) -> bool:
    """
    Determine whether the current turn belongs to an
    active order checkout.
    """

    # Explicit commands have priority.
    if _is_explicit_tracking_request(
        message
    ):
        return False

    if _is_explicit_cancel_request(
        message
    ):
        return False

    if _is_explicit_support_request(
        message
    ):
        return False

    # Explicitly starting a new order.
    if _is_new_order_request(
        message
    ):
        return True

    current_intent = state.get(
        "intent",
        "general",
    )

    if current_intent == "order_create":
        return True

    # Do not convert a normal product-search turn into checkout
    # merely because a product name was extracted.
    if current_intent == "product_search":
        return False

    existing_entities = (
        state.get(
            "entities",
            {},
        )
        or {}
    )

    product_id = entities.get("product_id")
    if product_id is None:
        product_id = existing_entities.get("product_id")

    product_name = entities.get("product_name")
    if not _has_value(product_name):
        product_name = existing_entities.get("product_name")

    quantity = entities.get("quantity")
    if quantity is None:
        quantity = existing_entities.get("quantity")

    address_id = state.get("selected_address_id")
    if address_id is None:
        address_id = entities.get("address_id")
    if address_id is None:
        address_id = existing_entities.get("address_id")

    payment_method = entities.get("payment_method")
    if not _has_value(payment_method):
        payment_method = existing_entities.get("payment_method")

    # A resolved product ID is the strongest checkout signal.
    if _has_value(product_id):
        return True

    # Product name is also a checkout signal before backend resolution.
    if _has_value(
        product_name
    ):
        return True

    # Quantity continuation.
    if _has_value(
        quantity
    ):
        return True

    # Address selection continuation.
    if _is_address_selection(
        state,
        message,
    ):
        return True

    # Payment continuation.
    if _is_payment_selection(
        message
    ):
        return True

    if (
        _has_value(
            payment_method
        )
        and (
            _has_value(
                product_name
            )
            or _has_value(
                quantity
            )
            or _has_value(
                address_id
            )
        )
    ):
        return True

    return False


# =========================================================
# Intent Resolution
# =========================================================


def resolve_transaction_intent(
    state: GraphState,
    entities: dict[str, Any],
    message: str,
) -> str:

    llm_intent = state.get(
        "intent",
        "general",
    )

    clean_message = (
        message or ""
    ).strip()

    # -----------------------------------------------------
    # 1. Explicit tracking
    # -----------------------------------------------------

    if _is_explicit_tracking_request(
        clean_message
    ):
        return "order_tracking"

    # -----------------------------------------------------
    # 2. Explicit cancellation
    # -----------------------------------------------------

    if _is_explicit_cancel_request(
        clean_message
    ):
        return "order_cancel"

    # -----------------------------------------------------
    # 3. Explicit support
    # -----------------------------------------------------

    if _is_explicit_support_request(
        clean_message
    ):
        return "customer_support"

    # -----------------------------------------------------
    # 4. Active checkout
    # -----------------------------------------------------

    if _is_active_order_checkout(
        state=state,
        entities=entities,
        message=clean_message,
    ):
        return "order_create"

    # -----------------------------------------------------
    # 5. Valid existing intent
    # -----------------------------------------------------

    valid_intents = {
        "product_search",
        "order_tracking",
        "order_cancel",
        "customer_support",
        "order_create",
        "general",
    }

    if llm_intent in valid_intents:
        return llm_intent

    return "general"


# =========================================================
# Missing Fields
# =========================================================


def get_missing_fields(
    intent: str,
    entities: EntityOutput,
) -> list[str]:
    """
    Determine missing checkout fields.

    IMPORTANT:
    The order of this list is intentional.

    Product
      ↓
    Quantity
      ↓
    Address
      ↓
    Payment

    Response node should ask only the FIRST missing field.
    """

    missing: list[str] = []

    # =====================================================
    # Product Search
    # =====================================================

    if intent == "product_search":

        if not entities.product_name:
            missing.append(
                "product_name"
            )

    # =====================================================
    # Order Creation
    # =====================================================

    elif intent == "order_create":

        # Product
        if (
            entities.product_id is None
            and not entities.product_name
        ):

            missing.append(
                "product_name"
            )

        # Quantity
        elif (
            entities.quantity is None
            or entities.quantity <= 0
        ):

            missing.append(
                "quantity"
            )

        # Address
        elif entities.address_id is None:

            missing.append(
                "address_selection"
            )

        # Payment
        elif not entities.payment_method:

            missing.append(
                "payment_method"
            )

    # =====================================================
    # Tracking
    # =====================================================

    elif intent == "order_tracking":

        if entities.order_id is None:

            missing.append(
                "order_id"
            )

    # =====================================================
    # Cancellation
    # =====================================================

    elif intent == "order_cancel":

        if entities.order_id is None:

            missing.append(
                "order_id"
            )

    return missing


# =========================================================
# LLM Entity Extraction
# =========================================================


def extract_entities(
    message: str,
    conversation_history: list[dict[str, Any]] | None = None,
) -> LLMEntityOutput:
    """
    Extract LLM-safe entities.

    product_id is intentionally not part of this model.


    Deterministic history recovery happens separately so
    critical checkout values do not depend entirely on the
    LLM.
    """

    if not message or not message.strip():

        return LLMEntityOutput()

    clean_message = message.strip()

    history_text = format_conversation_history(
        conversation_history
    )

    messages = [
        SystemMessage(
            content=ENTITY_SYSTEM_PROMPT
        ),

        HumanMessage(
            content=(
                "RECENT CONVERSATION:\n"
                "--------------------\n"
                f"{history_text}\n\n"

                "CURRENT USER MESSAGE:\n"
                "--------------------\n"
                f"{clean_message}\n\n"

                "Return the COMPLETE accumulated entity "
                "state. Preserve previous checkout values."
            )
        ),
    ]

    try:

        result: LLMEntityOutput = (
            structured_llm.invoke(
                messages
            )
        )

        if not isinstance(
            result,
            LLMEntityOutput,
        ):
            return LLMEntityOutput()

        return result

    except Exception as exc:

        print(
            "[ENTITY LLM ERROR]"
            f" {type(exc).__name__}: {exc}"
        )

        return LLMEntityOutput()


# =========================================================
# Entity Node
# =========================================================


def entity_node(
    state: GraphState,
) -> GraphState:
    """
    Main BuyQK entity-resolution node.

    This is intentionally deterministic around checkout
    state.

    Critical example:

        User:
            I want to order Amul milk

        Assistant:
            How much Amul milk would you like?

        User:
            3 packets

        Assistant:
            Please choose your delivery address.

        User:
            Use the selected delivery address.

    Final state MUST contain:

        product_name = Amul milk
        quantity = 3
        address_id = selected address

    and NOT ask for quantity again.
    """

    message = (
        state.get(
            "message",
            "",
        )
        or ""
    ).strip()

    original_intent = state.get(
        "intent",
        "general",
    )

    conversation_history = (
        state.get(
            "conversation_history",
            [],
        )
        or []
    )

    existing_entities = dict(
        state.get(
            "entities",
            {},
        )
        or {}
    )

    # =====================================================
    # New order reset
    # =====================================================
    #
    # If the user explicitly starts another order, don't
    # accidentally reuse the quantity/address/payment from
    # the previous completed order.
    #
    # =====================================================

    new_order = _is_new_order_request(
        message
    )

    # Only recover checkout fields from history while the graph is
    # actually in an order-creation flow. This prevents quantities,
    # addresses, and payment methods from old orders leaking into
    # unrelated product-search turns.
    checkout_context = (
        original_intent == "order_create"
        or _is_address_selection(
            state,
            message,
        )
        or _is_payment_selection(
            message
        )
    )

    if new_order:

        # Clear every order-specific value.
        # The new message will establish the new product.
        existing_entities.pop(
            "product_id",
            None,
        )

        existing_entities.pop(
            "product_name",
            None,
        )

        existing_entities.pop(
            "quantity",
            None,
        )

        existing_entities.pop(
            "address_id",
            None,
        )

        existing_entities.pop(
            "address_text",
            None,
        )

        existing_entities.pop(
            "payment_method",
            None,
        )

        existing_entities.pop(
            "order_id",
            None,
        )

    # =====================================================
    # LLM extraction
    # =====================================================

    extracted = extract_entities(
        message=message,
        conversation_history=conversation_history,
    )

    extracted_entities = (
        extracted.model_dump(
            exclude_none=True
        )
    )

    # =====================================================
    # Merge existing graph state
    # =====================================================

    entities = dict(
        existing_entities
    )

    for key, value in extracted_entities.items():

        if value is not None:

            entities[key] = value

    # =====================================================
    # IMPORTANT PRODUCT-ID RULE
    # =====================================================
    #
    # product_id is backend authoritative. The LLM model does not
    # contain this field, so it cannot overwrite it here.
    # Preserve an existing backend-resolved ID until the user
    # explicitly changes the product.
    #
    previous_product_name = existing_entities.get(
        "product_name"
    )
    existing_product_id = existing_entities.get(
        "product_id"
    )

    if existing_product_id is not None:
        try:
            existing_product_id = int(
                existing_product_id
            )
        except (TypeError, ValueError):
            existing_product_id = None

    if existing_product_id is not None and existing_product_id > 0:
        entities["product_id"] = existing_product_id
    else:
        entities.pop("product_id", None)

    # =====================================================
    # Deterministic current-message extraction
    # =====================================================

    explicit_quantity = detect_quantity(
        message
    )

    explicit_address = detect_address_text(
        message
    )

    explicit_address_id = detect_address_id(
        message
    )

    explicit_order_id = detect_order_id(
        message
    )

    explicit_payment = detect_payment_method(
        message
    )

    # =====================================================
    # Quantity
    # =====================================================

    if explicit_quantity is not None:

        entities["quantity"] = (
            explicit_quantity
        )

    # =====================================================
    # CRITICAL FIX:
    # Recover quantity from previous USER messages.
    # =====================================================

    elif (
        not new_order
        and checkout_context
    ):

        recovered_quantity = (
            recover_quantity_from_history(
                conversation_history
            )
        )

        if recovered_quantity is not None:

            # Only use history recovery when quantity is
            # not already known.
            if not entities.get(
                "quantity"
            ):

                entities["quantity"] = (
                    recovered_quantity
                )

    # =====================================================
    # Address text
    # =====================================================

    if explicit_address:

        entities["address_text"] = (
            explicit_address
        )

        # Natural-language address does not become a saved
        # address ID.
        if explicit_address_id is None:

            entities.pop(
                "address_id",
                None,
            )

    # =====================================================
    # Explicit address ID
    # =====================================================

    if explicit_address_id is not None:

        entities["address_id"] = (
            explicit_address_id
        )

        entities.pop(
            "address_text",
            None,
        )

    # =====================================================
    # Recover address ID from history
    # =====================================================

    elif (
        not new_order
        and checkout_context
    ):

        recovered_address_id = (
            recover_address_id_from_history(
                conversation_history
            )
        )

        if (
            recovered_address_id is not None
            and not entities.get(
                "address_id"
            )
        ):

            entities["address_id"] = (
                recovered_address_id
            )

    # =====================================================
    # Order ID
    # =====================================================

    if explicit_order_id is not None:

        entities["order_id"] = (
            explicit_order_id
        )

    elif (
        not new_order
        and original_intent in {
            "order_tracking",
            "order_cancel",
        }
    ):

        recovered_order_id = (
            recover_order_id_from_history(
                conversation_history
            )
        )

        if (
            recovered_order_id is not None
            and not entities.get(
                "order_id"
            )
        ):

            entities["order_id"] = (
                recovered_order_id
            )

    # =====================================================
    # Payment
    # =====================================================

    if explicit_payment is not None:

        entities["payment_method"] = (
            explicit_payment
        )

    elif (
        not new_order
        and checkout_context
    ):

        recovered_payment = (
            recover_payment_from_history(
                conversation_history
            )
        )

        if (
            recovered_payment is not None
            and not entities.get(
                "payment_method"
            )
        ):

            entities["payment_method"] = (
                recovered_payment
            )

    # =====================================================
    # Frontend selected address
    # =====================================================
    #
    # This is AUTHORITATIVE.
    #
    # AddressSelector should send:
    #
    # selected_address_id = 123
    #
    # That value must win over LLM inference.
    #
    # =====================================================

    selected_address_id = (
        state.get(
            "selected_address_id"
        )
    )

    if selected_address_id is not None:

        try:

            normalized_address_id = int(
                selected_address_id
            )

            if normalized_address_id > 0:

                entities["address_id"] = (
                    normalized_address_id
                )

                entities.pop(
                    "address_text",
                    None,
                )

        except (
            TypeError,
            ValueError,
        ):

            print(
                "[ENTITY]"
                " Invalid selected_address_id:"
                f" {selected_address_id!r}"
            )

    # =====================================================
    # Frontend selected payment
    # =====================================================
    #
    # PaymentSelector can send:
    #
    # state["payment_method"]
    #
    # This is authoritative.
    #
    # =====================================================

    selected_payment_method = (
        state.get(
            "payment_method"
        )
    )

    if selected_payment_method:

        normalized_payment = (
            str(
                selected_payment_method
            )
            .strip()
            .lower()
        )

        if normalized_payment in {
            "upi",
            "cod",
        }:

            entities["payment_method"] = (
                normalized_payment
            )

    # =====================================================
    # Normalize payment
    # =====================================================

    if entities.get(
        "payment_method"
    ):

        normalized_payment = (
            str(
                entities[
                    "payment_method"
                ]
            )
            .strip()
            .lower()
        )

        if normalized_payment in {
            "upi",
            "cod",
        }:

            entities["payment_method"] = (
                normalized_payment
            )

        else:

            entities.pop(
                "payment_method",
                None,
            )

    # =====================================================
    # Product fallback
    # =====================================================

    if not entities.get(
        "product_name"
    ):

        product = detect_product_fallback(
            message=message,
            conversation_history=conversation_history,
        )

        if product:

            entities["product_name"] = (
                product
            )

    # =====================================================
    # Normalize product
    # =====================================================

    if entities.get(
        "product_name"
    ):

        entities["product_name"] = (
            str(
                entities[
                    "product_name"
                ]
            )
            .strip()
        )

    # =====================================================
    # Product identity consistency
    # =====================================================
    #
    # If the user changed the product name, the previous product_id
    # is no longer valid. The later tool node must resolve the new
    # product name and write the new authoritative product_id.
    #
    current_product_name = entities.get(
        "product_name"
    )

    if (
        existing_product_id is not None
        and previous_product_name
        and current_product_name
        and str(previous_product_name).strip().casefold()
        != str(current_product_name).strip().casefold()
    ):
        entities.pop(
            "product_id",
            None,
        )

    # If there is no product name at all, do not carry a stale ID.
    if not current_product_name:
        entities.pop(
            "product_id",
            None,
        )

    # =====================================================
    # Product ID safety
    # =====================================================

    if entities.get("product_id") is not None:
        try:
            product_id = int(
                entities["product_id"]
            )

            if product_id > 0:
                entities["product_id"] = product_id
            else:
                entities.pop(
                    "product_id",
                    None,
                )

        except (TypeError, ValueError):
            entities.pop(
                "product_id",
                None,
            )

    # =====================================================
    # Quantity safety
    # =====================================================

    if entities.get(
        "quantity"
    ) is not None:

        try:

            quantity = int(
                entities[
                    "quantity"
                ]
            )

            if quantity > 0:

                entities["quantity"] = (
                    quantity
                )

            else:

                entities.pop(
                    "quantity",
                    None,
                )

        except (
            TypeError,
            ValueError,
        ):

            entities.pop(
                "quantity",
                None,
            )

    # =====================================================
    # Address ID safety
    # =====================================================

    if entities.get(
        "address_id"
    ) is not None:

        try:

            address_id = int(
                entities[
                    "address_id"
                ]
            )

            if address_id > 0:

                entities["address_id"] = (
                    address_id
                )

            else:

                entities.pop(
                    "address_id",
                    None,
                )

        except (
            TypeError,
            ValueError,
        ):

            entities.pop(
                "address_id",
                None,
            )

    # =====================================================
    # Order ID safety
    # =====================================================

    if entities.get(
        "order_id"
    ) is not None:

        try:

            order_id = int(
                entities[
                    "order_id"
                ]
            )

            if order_id > 0:

                entities["order_id"] = (
                    order_id
                )

            else:

                entities.pop(
                    "order_id",
                    None,
                )

        except (
            TypeError,
            ValueError,
        ):

            entities.pop(
                "order_id",
                None,
            )

    # =====================================================
    # Resolve final intent
    # =====================================================

    resolved_intent = (
        resolve_transaction_intent(
            state=state,
            entities=entities,
            message=message,
        )
    )

    # =====================================================
    # Build final structured entity object
    # =====================================================

    resolved_entities = EntityOutput(
        product_id=entities.get(
            "product_id"
        ),
        product_name=entities.get(
            "product_name"
        ),
        quantity=entities.get(
            "quantity"
        ),
        order_id=entities.get(
            "order_id"
        ),
        address_id=entities.get(
            "address_id"
        ),
        address_text=entities.get(
            "address_text"
        ),
        payment_method=entities.get(
            "payment_method"
        ),
    )

    # =====================================================
    # Determine missing fields
    # =====================================================

    missing_fields = (
        get_missing_fields(
            intent=resolved_intent,
            entities=resolved_entities,
        )
    )

    # =====================================================
    # Debug Logging
    # =====================================================

    final_entities = (
        resolved_entities.model_dump(
            exclude_none=True
        )
    )

    print(
        "\n"
        "[ENTITY NODE]"
        "\n"
        f"  message          = {message!r}"
        "\n"
        f"  intent_before    = {original_intent!r}"
        "\n"
        f"  intent_after     = {resolved_intent!r}"
        "\n"
        f"  new_order        = {new_order}"
        "\n"
        f"  selected_address = {selected_address_id!r}"
        "\n"
        f"  product_id       = {final_entities.get('product_id')!r}"
        "\n"
        f"  entities         = {final_entities}"
        "\n"
        f"  missing_fields   = {missing_fields}"
        "\n"
    )

    # =====================================================
    # Return Graph Updates
    # =====================================================

    return {
        "intent": resolved_intent,

        "entities": final_entities,

        # Convenience mirrors for downstream graph/tool nodes.
        # The authoritative product_id still comes from backend
        # resolution, never from the LLM.
        "product_id": final_entities.get("product_id"),
        "product_name": final_entities.get("product_name"),
        "quantity": final_entities.get("quantity"),
        "address_id": final_entities.get("address_id"),
        "payment_method": final_entities.get(
            "payment_method"
        ),

        "missing_fields": missing_fields,
    }