# =========================================================
# BuyQK AI - Tool Node
# =========================================================
#
# Phase 2
#
# Architecture:
#
#     User Message
#          ↓
#     Context Node
#          ↓
#     Entity Node
#          ↓
#     Planner Node
#          ↓
#     Policy Node
#          ↓
#     Decision Node
#          ↓
#     Tool Node
#          ↓
#     Backend Services
#          ↓
#     Tool Result
#          ↓
#     Response Node
#
# =========================================================
#
# RESPONSIBILITY
#
# This node EXECUTES an already-approved capability.
#
# It does NOT:
#
#   - understand natural language
#   - determine user intent
#   - decide what the user wants
#   - select the tool
#   - bypass policy
#   - calculate prices
#   - calculate tax
#   - calculate discounts
#   - calculate delivery charges
#   - calculate totals
#
# Planner:
#     decides WHAT should happen.
#
# Policy:
#     decides WHETHER the planned action is allowed.
#
# Decision:
#     routes the approved action.
#
# Tool Node:
#     EXECUTES the backend capability.
#
# Backend:
#     remains authoritative for business facts and mutations.
#
# =========================================================


from __future__ import annotations

from typing import Any

from sqlalchemy.orm import Session

from ai_engine.graph.state import GraphState

from backend.models.product import Product

from backend.services.product_service import (
    search_products,
    check_product_availability,
)

from backend.services.order_service import (
    create_order,
    get_order,
    cancel_order,
    build_order_bill,
)

from backend.services.support_service import (
    create_ticket,
)

from backend.services.address_service import (
    get_user_addresses,
)


# =========================================================
# Supported Tools
# =========================================================
#
# These are backend capabilities.
#
# The Tool Node does not choose between them.
# Decision/Planner have already selected the capability.
#
# =========================================================


SUPPORTED_TOOLS = {
    "search_products",
    "create_order",
    "track_order",
    "cancel_order",
    "create_support_ticket",
    "list_saved_addresses",
    "list_payment_methods",
}


# =========================================================
# Generic Helpers
# =========================================================


def _has_value(
    value: Any,
) -> bool:
    """
    Return True when a value is present.
    """

    if value is None:
        return False

    if isinstance(value, str):
        return bool(value.strip())

    return True


def _safe_int(
    value: Any,
) -> int | None:
    """
    Safely convert a value to a positive integer.
    """

    if value is None:
        return None

    if isinstance(value, bool):
        return None

    try:
        value = int(value)
    except (
        TypeError,
        ValueError,
    ):
        return None

    if value <= 0:
        return None

    return value


# =========================================================
# Planner / Tool Arguments
# =========================================================


def _get_tool_arguments(
    state: GraphState,
) -> dict[str, Any]:
    """
    Return structured arguments generated by the planner.

    Phase 2 preferred source:

        state["tool_args"]

    Supported compatibility sources:

        state["planner_args"]
        state["planner"]["tool_args"]
        state["planner"]["args"]

    Finally, existing entities are used as a compatibility
    fallback.

    IMPORTANT:

    These values describe WHAT the planner wants the tool
    to execute.

    Backend validation still determines whether those values
    are actually valid.
    """

    tool_args = state.get(
        "tool_args"
    )

    if isinstance(
        tool_args,
        dict,
    ):
        return dict(tool_args)

    planner_args = state.get(
        "planner_args"
    )

    if isinstance(
        planner_args,
        dict,
    ):
        return dict(planner_args)

    planner_state = state.get(
        "planner"
    )

    if isinstance(
        planner_state,
        dict,
    ):

        args = planner_state.get(
            "tool_args"
        )

        if isinstance(
            args,
            dict,
        ):
            return dict(args)

        args = planner_state.get(
            "args"
        )

        if isinstance(
            args,
            dict,
        ):
            return dict(args)

    entities = state.get(
        "entities",
        {},
    )

    if isinstance(
        entities,
        dict,
    ):
        return dict(entities)

    return {}


# =========================================================
# Entity Compatibility
# =========================================================


def _get_entities(
    state: GraphState,
) -> dict[str, Any]:
    """
    Return accumulated entity state.

    Entities are retained for backward compatibility.

    New Phase 2 tools should prefer structured tool_args.
    """

    entities = state.get(
        "entities",
        {},
    )

    if not isinstance(
        entities,
        dict,
    ):
        return {}

    return dict(
        entities
    )


# =========================================================
# Product Helpers
# =========================================================


def _product_value(
    product: Any,
    field: str,
) -> Any:
    """
    Safely read a Product model or dictionary field.
    """

    if isinstance(
        product,
        dict,
    ):
        return product.get(
            field
        )

    return getattr(
        product,
        field,
        None,
    )


def _product_id(
    product: Any,
) -> Any:
    return _product_value(
        product,
        "id",
    )


def _product_name(
    product: Any,
) -> str:
    return str(
        _product_value(
            product,
            "name",
        )
        or ""
    ).strip()


def _serialize_product(
    product: Any,
) -> dict[str, Any]:
    """
    Convert a Product into JSON-safe data.

    No business calculation occurs here.
    """

    return {
        "id": _product_value(
            product,
            "id",
        ),
        "name": _product_value(
            product,
            "name",
        ),
        "description": _product_value(
            product,
            "description",
        ),
        "brand": _product_value(
            product,
            "brand",
        ),
        "price": _product_value(
            product,
            "price",
        ),
        "stock": _product_value(
            product,
            "stock",
        ),
        "image_url": _product_value(
            product,
            "image_url",
        ),
        "is_available": _product_value(
            product,
            "is_available",
        ),
        "merchant_id": _product_value(
            product,
            "merchant_id",
        ),
        "category_id": _product_value(
            product,
            "category_id",
        ),
    }


# =========================================================
# Address Helpers
# =========================================================


def _get_address_id(
    state: GraphState,
    args: dict[str, Any],
    entities: dict[str, Any],
) -> Any:
    """
    Resolve the selected address identifier.

    Priority:

        1. tool_args
        2. selected_address_id in GraphState
        3. address_id in GraphState
        4. entities

    The actual ownership check is performed against the
    backend database.
    """

    address_id = args.get(
        "address_id"
    )

    if address_id is not None:
        return address_id

    address_id = args.get(
        "selected_address_id"
    )

    if address_id is not None:
        return address_id

    address_id = state.get(
        "selected_address_id"
    )

    if address_id is not None:
        return address_id

    address_id = state.get(
        "address_id"
    )

    if address_id is not None:
        return address_id

    address_id = entities.get(
        "address_id"
    )

    if address_id is not None:
        return address_id

    return entities.get(
        "selected_address_id"
    )


def _validate_address(
    db: Session,
    user_id: int,
    address_id: Any,
) -> tuple[bool, str | None]:
    """
    Validate address existence and ownership.

    Backend data is authoritative.
    """

    address_id = _safe_int(
        address_id
    )

    if address_id is None:
        return (
            False,
            "Please select a valid delivery address.",
        )

    try:

        addresses = get_user_addresses(
            db=db,
            user_id=user_id,
        )

    except Exception as exc:

        print(
            "[ADDRESS VALIDATION ERROR]",
            type(exc).__name__,
            str(exc),
        )

        return (
            False,
            "Unable to validate the selected delivery address.",
        )

    for address in addresses:

        current_id = getattr(
            address,
            "id",
            None,
        )

        current_id = _safe_int(
            current_id
        )

        if current_id == address_id:
            return (
                True,
                None,
            )

    return (
        False,
        "The selected delivery address does not belong to this user.",
    )


def _serialize_address(
    address: Any,
) -> dict[str, Any]:
    """
    Serialize backend address data.
    """

    return {
        "id": getattr(
            address,
            "id",
            None,
        ),
        "label": getattr(
            address,
            "label",
            None,
        ),
        "address": getattr(
            address,
            "address",
            None,
        ),
        "address_line1": getattr(
            address,
            "address_line1",
            None,
        ),
        "address_line2": getattr(
            address,
            "address_line2",
            None,
        ),
        "city": getattr(
            address,
            "city",
            None,
        ),
        "state": getattr(
            address,
            "state",
            None,
        ),
        "postal_code": getattr(
            address,
            "postal_code",
            None,
        ),
        "pincode": getattr(
            address,
            "pincode",
            None,
        ),
    }


# =========================================================
# Payment Helpers
# =========================================================


def _get_payment_method(
    state: GraphState,
    args: dict[str, Any],
    entities: dict[str, Any],
) -> str | None:
    """
    Resolve the selected payment method.

    The AI/planner may provide the requested method.

    The backend remains responsible for determining whether
    that method is actually valid/available.
    """

    payment_method = args.get(
        "payment_method"
    )

    if payment_method is None:
        payment_method = args.get(
            "selected_payment_method"
        )

    if payment_method is None:
        payment_method = state.get(
            "selected_payment_method"
        )

    if payment_method is None:
        payment_method = state.get(
            "payment_method"
        )

    if payment_method is None:
        payment_method = entities.get(
            "payment_method"
        )

    if payment_method is None:
        return None

    normalized = str(
        payment_method
    ).strip().lower()

    return normalized or None


# =========================================================
# Quantity
# =========================================================


def _normalize_quantity(
    quantity: Any,
) -> int | None:
    """
    Normalize quantity into a positive integer.
    """

    if quantity is None:
        return None

    if isinstance(
        quantity,
        bool,
    ):
        return None

    try:
        quantity = int(
            quantity
        )
    except (
        TypeError,
        ValueError,
    ):
        return None

    if quantity <= 0:
        return None

    return quantity


# =========================================================
# Order Items
# =========================================================


def _extract_order_items(
    args: dict[str, Any],
    entities: dict[str, Any],
) -> list[dict[str, Any]]:
    """
    Normalize planner tool arguments into backend order items.

    Preferred Phase 2 structure:

        tool_args = {
            "items": [
                {
                    "product_id": 12,
                    "quantity": 2
                }
            ]
        }

    Backward-compatible structures are also accepted.
    """

    raw_items = args.get(
        "items"
    )

    if raw_items is None:
        raw_items = args.get(
            "cart_items"
        )

    if raw_items is None:
        raw_items = entities.get(
            "items"
        )

    if raw_items is None:
        raw_items = entities.get(
            "cart_items"
        )

    # =====================================================
    # Multi-item
    # =====================================================

    if isinstance(
        raw_items,
        list,
    ):

        normalized_items: list[
            dict[str, Any]
        ] = []

        for item in raw_items:

            if not isinstance(
                item,
                dict,
            ):
                continue

            product_id = item.get(
                "product_id"
            )

            product_name = item.get(
                "product_name"
            )

            quantity = _normalize_quantity(
                item.get(
                    "quantity"
                )
            )

            if quantity is None:
                continue

            if (
                product_id is None
                and not _has_value(
                    product_name
                )
            ):
                continue

            normalized_item = {
                "quantity": quantity,
            }

            if product_id is not None:

                normalized_item[
                    "product_id"
                ] = product_id

            else:

                normalized_item[
                    "product_name"
                ] = str(
                    product_name
                ).strip()

            normalized_items.append(
                normalized_item
            )

        return normalized_items

    # =====================================================
    # Single item
    # =====================================================

    product_id = args.get(
        "product_id"
    )

    if product_id is None:
        product_id = entities.get(
            "product_id"
        )

    product_name = args.get(
        "product_name"
    )

    if product_name is None:
        product_name = entities.get(
            "product_name"
        )

    quantity = args.get(
        "quantity"
    )

    if quantity is None:
        quantity = entities.get(
            "quantity"
        )

    quantity = _normalize_quantity(
        quantity
    )

    if quantity is None:
        return []

    if (
        product_id is None
        and not _has_value(
            product_name
        )
    ):
        return []

    item = {
        "quantity": quantity,
    }

    if product_id is not None:

        item[
            "product_id"
        ] = product_id

    else:

        item[
            "product_name"
        ] = str(
            product_name
        ).strip()

    return [
        item
    ]


# =========================================================
# Product Resolution
# =========================================================


def _resolve_product(
    db: Session,
    product_name: str,
) -> tuple[
    Product | None,
    list[Product],
]:
    """
    Resolve a natural-language product name against the
    authoritative Product table.

    This is an execution-time backend lookup.

    The LLM does NOT get to invent the product ID.

    NOTE:
    Product selection logic is intentionally delegated as much
    as possible to product_service.search_products().
    """

    if not _has_value(
        product_name
    ):
        return (
            None,
            [],
        )

    query = str(
        product_name
    ).strip()

    try:

        results = search_products(
            db=db,
            query=query,
        )

    except Exception as exc:

        print(
            "[PRODUCT SEARCH ERROR]",
            type(exc).__name__,
            str(exc),
        )

        return (
            None,
            [],
        )

    if results is None:
        return (
            None,
            [],
        )

    if not isinstance(
        results,
        list,
    ):
        results = [
            results
        ]

    products = [
        product
        for product in results
        if product is not None
    ]

    if not products:
        return (
            None,
            [],
        )

    # -----------------------------------------------------
    # Exact name match first
    # -----------------------------------------------------

    normalized_query = query.strip().casefold()

    exact_matches = []

    for product in products:

        name = _product_name(
            product
        ).casefold()

        if name == normalized_query:
            exact_matches.append(
                product
            )

    if len(exact_matches) == 1:
        return (
            exact_matches[0],
            products,
        )

    if len(exact_matches) > 1:
        return (
            None,
            exact_matches,
        )

    # -----------------------------------------------------
    # If service returned one candidate, accept it.
    # -----------------------------------------------------

    if len(products) == 1:
        return (
            products[0],
            products,
        )

    # -----------------------------------------------------
    # Multiple candidates are ambiguous.
    # -----------------------------------------------------

    return (
        None,
        products,
    )


# =========================================================
# Bill Serialization
# =========================================================


def _serialize_bill(
    bill: Any,
) -> dict[str, Any] | None:
    """
    Preserve the complete authoritative backend bill.

    This node does NOT calculate billing.
    """

    if not isinstance(
        bill,
        dict,
    ):
        return None

    return dict(
        bill
    )


# =========================================================
# Tool Result Helpers
# =========================================================


def _error_result(
    error_type: str,
    message: str,
    **extra: Any,
) -> GraphState:
    """
    Build a consistent tool failure response.
    """

    return {
        "tool_result": {
            "success": False,
            "type": error_type,
            "error": message,
            **extra,
        }
    }


# =========================================================
# Tool Node
# =========================================================


def tool_node(
    state: GraphState,
    db: Session,
) -> GraphState:
    """
    Execute the capability selected by the planner/policy/decision
    pipeline.

    ========================================================
    Phase 2 execution contract
    ========================================================

    Planner:
        chooses action/tool

    Policy:
        approves or rejects

    Decision:
        routes

    Tool Node:
        executes

    Backend:
        verifies authoritative facts

    ========================================================

    This node must never bypass backend validation.
    """

    # =====================================================
    # Read approved tool
    # =====================================================

    tool_name = state.get(
        "tool_name"
    )

    if isinstance(
        tool_name,
        str,
    ):
        tool_name = tool_name.strip().casefold()

    entities = _get_entities(
        state
    )

    tool_args = _get_tool_arguments(
        state
    )

    user_id = state.get(
        "user_id"
    )

    checkout_id = state.get(
        "checkout_id"
    )

    print(
        "\n"
        "====================================================\n"
        "[TOOL NODE]\n"
        "====================================================\n"
        f"tool_name  = {tool_name!r}\n"
        f"user_id    = {user_id!r}\n"
        f"tool_args  = {tool_args!r}\n"
        f"checkout_id= {checkout_id!r}\n"
        "====================================================\n"
    )

    # =====================================================
    # No tool
    # =====================================================

    if not tool_name:

        return {
            "tool_result": None,
        }

    # =====================================================
    # Unsupported tool
    # =====================================================

    if tool_name not in SUPPORTED_TOOLS:

        return _error_result(
            "unsupported_tool",
            f"Unsupported tool: {tool_name}",
        )

    # =====================================================
    # SEARCH PRODUCTS
    # =====================================================

    if tool_name == "search_products":

        query = tool_args.get(
            "query"
        )

        if query is None:
            query = tool_args.get(
                "product_name"
            )

        if query is None:
            query = entities.get(
                "product_name"
            )

        if not _has_value(
            query
        ):

            return _error_result(
                "product_search",
                "Product search query is required.",
            )

        try:

            products = search_products(
                db=db,
                query=str(
                    query
                ).strip(),
            )

            if products is None:
                products = []

            if not isinstance(
                products,
                list,
            ):
                products = [
                    products
                ]

            return {
                "tool_result": {
                    "success": True,
                    "type": "product_search",
                    "query": str(
                        query
                    ).strip(),
                    "products": [
                        _serialize_product(
                            product
                        )
                        for product in products
                    ],
                }
            }

        except Exception as exc:

            print(
                "[TOOL search_products ERROR]",
                type(exc).__name__,
                str(exc),
            )

            return _error_result(
                "product_search",
                str(exc),
            )

    # =====================================================
    # LIST SAVED ADDRESSES
    # =====================================================

    if tool_name == "list_saved_addresses":

        if user_id is None:

            return _error_result(
                "address_selection",
                "User ID is required to load saved addresses.",
            )

        user_id_int = _safe_int(
            user_id
        )

        if user_id_int is None:

            return _error_result(
                "address_selection",
                "Invalid user ID.",
            )

        try:

            addresses = get_user_addresses(
                db=db,
                user_id=user_id_int,
            )

            return {
                "tool_result": {
                    "success": True,
                    "type": "address_selection",
                    "addresses": [
                        _serialize_address(
                            address
                        )
                        for address in addresses
                    ],
                    "allow_new": True,
                }
            }

        except Exception as exc:

            print(
                "[TOOL list_saved_addresses ERROR]",
                type(exc).__name__,
                str(exc),
            )

            return _error_result(
                "address_selection",
                str(exc),
            )

    # =====================================================
    # LIST PAYMENT METHODS
    # =====================================================

    if tool_name == "list_payment_methods":

        try:

            from backend.services.order_service import (
                SUPPORTED_PAYMENT_METHODS,
            )

            configured_methods = (
                SUPPORTED_PAYMENT_METHODS
            )

            if configured_methods is None:
                configured_methods = set()

            methods = []

            for method in configured_methods:

                if isinstance(
                    method,
                    dict,
                ):

                    methods.append(
                        dict(method)
                    )

                    continue

                method_id = str(
                    method
                ).strip()

                if not method_id:
                    continue

                methods.append(
                    {
                        "id": method_id,
                        "label": method_id.replace(
                            "_",
                            " ",
                        ).replace(
                            "-",
                            " ",
                        ).title(),
                    }
                )

            return {
                "tool_result": {
                    "success": True,
                    "type": "payment_selection",
                    "methods": methods,
                }
            }

        except ImportError:

            return _error_result(
                "payment_selection",
                "Payment methods are not configured by the backend.",
                methods=[],
            )

        except Exception as exc:

            print(
                "[TOOL list_payment_methods ERROR]",
                type(exc).__name__,
                str(exc),
            )

            return _error_result(
                "payment_selection",
                str(exc),
                methods=[],
            )

    # =====================================================
    # CREATE ORDER
    # =====================================================

    if tool_name == "create_order":

        # -------------------------------------------------
        # User
        # -------------------------------------------------

        user_id_int = _safe_int(
            user_id
        )

        if user_id_int is None:

            return _error_result(
                "order_error",
                "Valid user ID is required.",
            )

        # -------------------------------------------------
        # Items
        # -------------------------------------------------

        order_items = _extract_order_items(
            tool_args,
            entities,
        )

        if not order_items:

            return _error_result(
                "product_required",
                "Product and quantity are required before placing the order.",
            )

        # -------------------------------------------------
        # Address
        # -------------------------------------------------

        address_id = _get_address_id(
            state,
            tool_args,
            entities,
        )

        address_id = _safe_int(
            address_id
        )

        if address_id is None:

            return _error_result(
                "address_selection",
                "Please select a valid delivery address before placing the order.",
            )

        address_valid, address_error = (
            _validate_address(
                db=db,
                user_id=user_id_int,
                address_id=address_id,
            )
        )

        if not address_valid:

            return _error_result(
                "address_selection",
                address_error
                or "Invalid delivery address.",
            )

        # -------------------------------------------------
        # Payment
        # -------------------------------------------------

        payment_method = _get_payment_method(
            state,
            tool_args,
            entities,
        )

        if payment_method is None:

            return _error_result(
                "payment_selection",
                "Please select a payment method before placing the order.",
            )

        # -------------------------------------------------
        # Resolve every product
        # -------------------------------------------------

        resolved_items: list[
            dict[str, Any]
        ] = []

        authoritative_products: list[
            Product
        ] = []

        for item in order_items:

            product_id = item.get(
                "product_id"
            )

            product_name = item.get(
                "product_name"
            )

            quantity = _normalize_quantity(
                item.get(
                    "quantity"
                )
            )

            if quantity is None:

                return _error_result(
                    "quantity_required",
                    "Quantity must be a positive number.",
                )

            # ---------------------------------------------
            # Product ID supplied
            # ---------------------------------------------

            if product_id is not None:

                product_id = _safe_int(
                    product_id
                )

                if product_id is None:

                    return _error_result(
                        "product_invalid",
                        "The selected product has an invalid product ID.",
                    )

                product = (
                    db.query(Product)
                    .filter(
                        Product.id
                        == product_id
                    )
                    .first()
                )

                if product is None:

                    return _error_result(
                        "product_not_found",
                        f"Product {product_id} does not exist.",
                    )

            # ---------------------------------------------
            # Product name supplied
            # ---------------------------------------------

            else:

                product, candidates = (
                    _resolve_product(
                        db=db,
                        product_name=str(
                            product_name
                        ).strip(),
                    )
                )

                if product is None:

                    if candidates:

                        return _error_result(
                            "product_selection",
                            (
                                "Multiple products match "
                                f"'{product_name}'. "
                                "Please choose one."
                            ),
                            products=[
                                _serialize_product(
                                    candidate
                                )
                                for candidate in candidates
                            ],
                        )

                    return _error_result(
                        "product_not_found",
                        (
                            "No product found for "
                            f"'{product_name}'."
                        ),
                    )

                product_id = _safe_int(
                    _product_id(
                        product
                    )
                )

                if product_id is None:

                    return _error_result(
                        "product_invalid",
                        "The resolved product has no valid product ID.",
                    )

            # ---------------------------------------------
            # Re-read authoritative product
            # ---------------------------------------------

            authoritative_product = (
                db.query(Product)
                .filter(
                    Product.id
                    == product_id
                )
                .first()
            )

            if authoritative_product is None:

                return _error_result(
                    "product_not_found",
                    f"Product {product_id} does not exist.",
                )

            # ---------------------------------------------
            # Availability
            # ---------------------------------------------

            try:

                available = (
                    check_product_availability(
                        db=db,
                        product_id=product_id,
                        quantity=quantity,
                    )
                )

            except Exception as exc:

                print(
                    "[AVAILABILITY ERROR]",
                    type(exc).__name__,
                    str(exc),
                )

                return _error_result(
                    "availability_error",
                    str(exc),
                )

            if not available:

                display_name = (
                    _product_name(
                        authoritative_product
                    )
                    or str(
                        product_name
                        or product_id
                    )
                )

                return _error_result(
                    "product_unavailable",
                    (
                        f"'{display_name}' is not "
                        "available in the requested quantity."
                    ),
                    product=_serialize_product(
                        authoritative_product
                    ),
                    quantity=quantity,
                )

            resolved_items.append(
                {
                    "product_id": product_id,
                    "quantity": quantity,
                }
            )

            authoritative_products.append(
                authoritative_product
            )

        # -------------------------------------------------
        # Create order through backend
        # -------------------------------------------------

        print(
            "[CREATE ORDER]"
            f" user_id={user_id_int}"
            f" items={resolved_items}"
            f" address_id={address_id}"
            f" payment={payment_method}"
            f" checkout_id={checkout_id!r}"
        )

        try:

            order = create_order(
                db=db,
                user_id=user_id_int,
                address_id=address_id,
                items=resolved_items,
                payment_method=payment_method,
                checkout_id=checkout_id,
            )

        except ValueError as exc:

            print(
                "[CREATE ORDER VALUE ERROR]",
                str(exc),
            )

            return _error_result(
                "order_error",
                str(exc),
            )

        except Exception as exc:

            print(
                "[CREATE ORDER ERROR]",
                type(exc).__name__,
                str(exc),
            )

            return _error_result(
                "order_error",
                "I could not place the order because of a backend error.",
            )

        # -------------------------------------------------
        # Verify order ID
        # -------------------------------------------------

        order_id = getattr(
            order,
            "id",
            None,
        )

        order_id = _safe_int(
            order_id
        )

        if order_id is None:

            return _error_result(
                "order_error",
                "Order creation completed but no order ID was returned.",
            )

        # -------------------------------------------------
        # Obtain authoritative bill
        # -------------------------------------------------

        bill = getattr(
            order,
            "_buyqk_bill",
            None,
        )

        if bill is None:

            try:

                bill = build_order_bill(
                    db=db,
                    order=order,
                )

            except Exception as exc:

                print(
                    "[BILL GENERATION ERROR]",
                    type(exc).__name__,
                    str(exc),
                )

                return {
                    "tool_result": {
                        "success": False,
                        "type": "bill_error",
                        "error": (
                            "Order was created, but "
                            "the bill could not be generated."
                        ),
                        "order_id": order_id,
                    },
                    "order_id": order_id,
                    "checkout_id": checkout_id,
                    "checkout_status": "completed",
                    "order_created": True,
                }

        bill = _serialize_bill(
            bill
        )

        if bill is None:

            return {
                "tool_result": {
                    "success": False,
                    "type": "bill_error",
                    "error": (
                        "Order was created, but "
                        "the bill data is invalid."
                    ),
                    "order_id": order_id,
                    "checkout_id": checkout_id,
                    "checkout_status": "completed",
                    "order_created": True,
                },
                "order_id": order_id,
                "checkout_id": checkout_id,
                "checkout_status": "completed",
                "order_created": True,
            }

        # -------------------------------------------------
        # Preserve backend order ID
        # -------------------------------------------------

        bill["order_id"] = order_id

        billing_items = bill.get(
            "items"
        )

        subtotal = bill.get(
            "subtotal"
        )

        delivery_charge = bill.get(
            "delivery_charge"
        )

        discount = bill.get(
            "discount"
        )

        tax = bill.get(
            "tax"
        )

        total_amount = bill.get(
            "total"
        )

        currency = bill.get(
            "currency"
        )

        billing_payment_method = bill.get(
            "payment_method"
        )

        # -------------------------------------------------
        # Return authoritative transaction state
        # -------------------------------------------------

        updated_entities = dict(
            entities
        )

        if len(
            resolved_items
        ) == 1:

            updated_entities[
                "product_id"
            ] = resolved_items[0][
                "product_id"
            ]

            updated_entities[
                "quantity"
            ] = resolved_items[0][
                "quantity"
            ]

            if authoritative_products:

                updated_entities[
                    "product_name"
                ] = _product_name(
                    authoritative_products[0]
                )

        updated_entities[
            "address_id"
        ] = address_id

        updated_entities[
            "payment_method"
        ] = payment_method

        return {
            "tool_result": {
                "success": True,
                "type": "order_success",
                "order_id": order_id,
                "checkout_id": checkout_id,
                "checkout_status": "completed",
                "order_created": True,
                "status": getattr(
                    order,
                    "status",
                    None,
                ),
                "payment_status": getattr(
                    order,
                    "payment_status",
                    None,
                ),
                "payment_method": billing_payment_method,
                "total_amount": total_amount,
                "bill": bill,
                "purchase_summary": {
                    "items": billing_items,
                    "subtotal": subtotal,
                    "delivery_charge": delivery_charge,
                    "discount": discount,
                    "tax": tax,
                    "total": total_amount,
                    "currency": currency,
                    "payment_method": billing_payment_method,
                },
            },
            "entities": updated_entities,
            "checkout_id": checkout_id,
            "checkout_status": "completed",
            "order_created": True,
            "order_id": order_id,
            "product_id": (
                resolved_items[0][
                    "product_id"
                ]
                if len(
                    resolved_items
                ) == 1
                else state.get(
                    "product_id"
                )
            ),
            "quantity": (
                resolved_items[0][
                    "quantity"
                ]
                if len(
                    resolved_items
                ) == 1
                else state.get(
                    "quantity"
                )
            ),
            "address_id": address_id,
            "selected_address_id": address_id,
            "payment_method": payment_method,
            "selected_payment_method": payment_method,
            "billing": bill,
            "bill": bill,
            "billing_items": billing_items,
            "subtotal": subtotal,
            "delivery_charge": delivery_charge,
            "discount": discount,
            "tax": tax,
            "total_amount": total_amount,
            "currency": currency,
            "billing_payment_method": billing_payment_method,
            "awaiting_order_tracking_confirmation": True,
        }

    # =====================================================
    # TRACK ORDER
    # =====================================================

    if tool_name == "track_order":

        order_id = tool_args.get(
            "order_id"
        )

        if order_id is None:
            order_id = entities.get(
                "order_id"
            )

        if order_id is None:
            order_id = state.get(
                "order_id"
            )

        order_id = _safe_int(
            order_id
        )

        if order_id is None:

            return _error_result(
                "order_tracking",
                "Order ID is required.",
            )

        try:

            order = get_order(
                db=db,
                order_id=order_id,
            )

        except Exception as exc:

            print(
                "[TRACK ORDER ERROR]",
                type(exc).__name__,
                str(exc),
            )

            return _error_result(
                "order_tracking",
                str(exc),
            )

        if order is None:

            return _error_result(
                "order_tracking",
                f"Order {order_id} does not exist.",
            )

        # -------------------------------------------------
        # Authorization
        # -------------------------------------------------

        user_id_int = _safe_int(
            user_id
        )

        order_user_id = getattr(
            order,
            "user_id",
            None,
        )

        order_user_id = _safe_int(
            order_user_id
        )

        if (
            user_id_int is not None
            and order_user_id != user_id_int
        ):

            return _error_result(
                "order_tracking",
                "You are not authorized to view this order.",
            )

        # -------------------------------------------------
        # Authoritative bill
        # -------------------------------------------------

        try:

            bill = build_order_bill(
                db=db,
                order=order,
            )

        except Exception:

            bill = None

        serialized_bill = (
            _serialize_bill(
                bill
            )
            if bill
            else None
        )

        result: GraphState = {
            "tool_result": {
                "success": True,
                "type": "tracking",
                "order_id": getattr(
                    order,
                    "id",
                    order_id,
                ),
                "status": getattr(
                    order,
                    "status",
                    None,
                ),
                "payment_status": getattr(
                    order,
                    "payment_status",
                    None,
                ),
                "total_amount": getattr(
                    order,
                    "total_amount",
                    None,
                ),
                "bill": serialized_bill,
            },
            "order_id": getattr(
                order,
                "id",
                order_id,
            ),
            "awaiting_order_tracking_confirmation": False,
        }

        if serialized_bill is not None:

            result.update(
                {
                    "billing": serialized_bill,
                    "bill": serialized_bill,
                    "billing_items": serialized_bill.get(
                        "items",
                        [],
                    ),
                    "subtotal": serialized_bill.get(
                        "subtotal"
                    ),
                    "delivery_charge": serialized_bill.get(
                        "delivery_charge"
                    ),
                    "discount": serialized_bill.get(
                        "discount"
                    ),
                    "tax": serialized_bill.get(
                        "tax"
                    ),
                    "total_amount": serialized_bill.get(
                        "total"
                    ),
                    "currency": serialized_bill.get(
                        "currency"
                    ),
                    "billing_payment_method": serialized_bill.get(
                        "payment_method"
                    ),
                }
            )

        return result

    # =====================================================
    # CANCEL ORDER
    # =====================================================

    if tool_name == "cancel_order":

        user_id_int = _safe_int(
            user_id
        )

        if user_id_int is None:

            return _error_result(
                "order_cancel",
                "Valid user ID is required.",
            )

        order_id = tool_args.get(
            "order_id"
        )

        if order_id is None:
            order_id = entities.get(
                "order_id"
            )

        if order_id is None:
            order_id = state.get(
                "order_id"
            )

        order_id = _safe_int(
            order_id
        )

        if order_id is None:

            return _error_result(
                "order_cancel",
                "Order ID is required.",
            )

        try:

            order = cancel_order(
                db=db,
                order_id=order_id,
                user_id=user_id_int,
            )

            return {
                "tool_result": {
                    "success": True,
                    "type": "order_cancelled",
                    "order_id": getattr(
                        order,
                        "id",
                        order_id,
                    ),
                    "status": getattr(
                        order,
                        "status",
                        None,
                    ),
                },
                "entities": dict(
                    entities
                ),
                "order_id": order_id,
            }

        except ValueError as exc:

            return _error_result(
                "order_cancelled",
                str(exc),
            )

        except Exception as exc:

            print(
                "[CANCEL ORDER ERROR]",
                type(exc).__name__,
                str(exc),
            )

            return _error_result(
                "order_cancelled",
                str(exc),
            )

    # =====================================================
    # CREATE SUPPORT TICKET
    # =====================================================

    if tool_name == "create_support_ticket":

        user_id_int = _safe_int(
            user_id
        )

        if user_id_int is None:

            return _error_result(
                "support_ticket",
                "Valid user ID is required.",
            )

        order_id = tool_args.get(
            "order_id"
        )

        if order_id is None:
            order_id = entities.get(
                "order_id"
            )

        if order_id is None:
            order_id = state.get(
                "order_id"
            )

        order_id = _safe_int(
            order_id
        )

        message = tool_args.get(
            "message"
        )

        if message is None:
            message = tool_args.get(
                "description"
            )

        if message is None:
            message = state.get(
                "message",
                "",
            )

        if not _has_value(
            message
        ):

            return _error_result(
                "support_ticket",
                "Support message is required.",
            )

        try:

            ticket = create_ticket(
                db=db,
                user_id=user_id_int,
                subject="BuyQK Customer Support",
                description=str(
                    message
                ),
                order_id=order_id,
            )

            return {
                "tool_result": {
                    "success": True,
                    "type": "support_ticket",
                    "ticket_id": getattr(
                        ticket,
                        "id",
                        None,
                    ),
                    "status": getattr(
                        ticket,
                        "status",
                        None,
                    ),
                }
            }

        except ValueError as exc:

            return _error_result(
                "support_ticket",
                str(exc),
            )

        except Exception as exc:

            print(
                "[SUPPORT TICKET ERROR]",
                type(exc).__name__,
                str(exc),
            )

            return _error_result(
                "support_ticket",
                str(exc),
            )

    # =====================================================
    # Safety Fallback
    # =====================================================

    print(
        "[TOOL ERROR]"
        f" Unsupported tool: {tool_name}"
    )

    return _error_result(
        "unsupported_tool",
        f"Unsupported tool: {tool_name}",
    )