"""
The ConversationHistory model will:
Store which user had the conversation.
Group messages using a session_id.
Store the detected intent.
Store the user's message.
Store the AI's response.
Preserve conversation history in SQLite.
Allow us to inspect previous conversations.
Provide persistent history independently of Redis.
"""

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.database.base import Base


class ConversationHistory(Base):
    """
    Represents a single conversation exchange between
    a BuyQK user and the AI assistant.
    """

    __tablename__ = "conversation_history"

    # Unique identifier for the conversation record
    id: Mapped[int] = mapped_column(
        primary_key=True,
        autoincrement=True
    )

    # User associated with this conversation
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True
    )

    # Groups multiple messages into one conversation session
    session_id: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True
    )

    # Detected user intent for this message
    #
    # Examples:
    # grocery_order
    # food_order
    # medicine_order
    # electronics_order
    # service_booking
    # order_tracking
    # order_cancellation
    # customer_support
    intent: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
        index=True
    )

    # Message sent by the user
    message: Mapped[str] = mapped_column(
        Text,
        nullable=False
    )

    # Response generated by the AI assistant
    response: Mapped[str] = mapped_column(
        Text,
        nullable=False
    )

    # Conversation record creation timestamp
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True
    )

    # Relationship with User
    user = relationship(
        "User",
        back_populates="conversation_history"
    )