# backend/database/vector_store.py
# Purpose:
# Provides persistent storage for the BuyQK FAISS vector database.
#
# It stores:
#   1. FAISS vector index
#   2. Document metadata/text associated with each vector
#
# This is used only for the knowledge-base / RAG layer.
# Transactional data remains in SQLite.


import json
from pathlib import Path
from typing import Any

from backend.database.vector_db import VectorDB


class VectorStore:
    """
    Persistent wrapper around the FAISS VectorDB.

    Responsibilities:
    - Add documents and embeddings
    - Search the vector database
    - Save FAISS index to disk
    - Save document metadata to JSON
    - Load the complete vector store
    - Clear the vector store
    """

    def __init__(
        self,
        dimension: int,
        store_dir: str = "data/vector_store",
    ):
        """
        Initialize the persistent vector store.

        Args:
            dimension:
                Dimension of the embedding vectors.

            store_dir:
                Directory where the FAISS index and metadata
                will be stored.
        """

        self.store_dir = Path(store_dir)

        # FAISS index location
        self.index_path = (
            self.store_dir / "index.faiss"
        )

        # Document metadata location
        self.documents_path = (
            self.store_dir / "documents.json"
        )

        # Underlying FAISS vector database
        self.vector_db = VectorDB(
            dimension=dimension,
            index_path=str(self.index_path),
        )

    # ---------------------------------------------------------
    # Add documents
    # ---------------------------------------------------------

    def add_documents(
        self,
        embeddings: list[list[float]],
        documents: list[dict[str, Any]],
    ) -> None:
        """
        Add document embeddings and metadata.

        Args:
            embeddings:
                Embeddings generated by the embedding model.

            documents:
                Metadata associated with each embedding.
        """

        self.vector_db.add_documents(
            embeddings=embeddings,
            documents=documents,
        )

    # ---------------------------------------------------------
    # Search
    # ---------------------------------------------------------

    def search(
        self,
        query_embedding: list[float],
        top_k: int = 5,
    ) -> list[dict[str, Any]]:
        """
        Search for the most relevant knowledge-base documents.

        Args:
            query_embedding:
                Embedding generated from the user's query.

            top_k:
                Number of results to return.

        Returns:
            Matching documents with similarity distance.
        """

        return self.vector_db.search(
            query_embedding=query_embedding,
            top_k=top_k,
        )

    # ---------------------------------------------------------
    # Save
    # ---------------------------------------------------------

    def save(self) -> None:
        """
        Persist the FAISS index and document metadata.
        """

        # Make sure the directory exists.
        self.store_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        # Save FAISS index.
        self.vector_db.save()

        # Save associated document metadata.
        with open(
            self.documents_path,
            "w",
            encoding="utf-8",
        ) as file:

            json.dump(
                self.vector_db.documents,
                file,
                ensure_ascii=False,
                indent=2,
            )

    # ---------------------------------------------------------
    # Load
    # ---------------------------------------------------------

    def load(self) -> None:
        """
        Load the FAISS index and document metadata from disk.
        """

        if not self.index_path.exists():
            raise FileNotFoundError(
                f"FAISS index not found: "
                f"{self.index_path}"
            )

        if not self.documents_path.exists():
            raise FileNotFoundError(
                f"Document metadata not found: "
                f"{self.documents_path}"
            )

        # Load FAISS index.
        self.vector_db.load()

        # Load document metadata.
        with open(
            self.documents_path,
            "r",
            encoding="utf-8",
        ) as file:

            documents = json.load(file)

        self.vector_db.documents = documents

        # Safety check:
        # number of vectors should match number of documents.
        if self.vector_db.count() != len(
            self.vector_db.documents
        ):
            raise ValueError(
                "Vector/document count mismatch. "
                "The FAISS index and documents.json "
                "do not contain the same number of records."
            )

    # ---------------------------------------------------------
    # Clear
    # ---------------------------------------------------------

    def clear(self) -> None:
        """
        Clear the vector database and remove
        persisted vector-store files.
        """

        self.vector_db.clear()

        if self.index_path.exists():
            self.index_path.unlink()

        if self.documents_path.exists():
            self.documents_path.unlink()

    # ---------------------------------------------------------
    # Count
    # ---------------------------------------------------------

    def count(self) -> int:
        """
        Return the number of stored documents.
        """

        return self.vector_db.count()